### ISSUE TITLE
F_SETLK gets stuck

### ISSUE THREAD

**Issue by njaard** [moosefs/moosefs#103]
My program uses sqlite3. It opens and closes files (with WAL) very often on a moosefs filesystem. (That is to say, my program starts, it opens a sqlite3 database, does a small read or write and then exits. There was previously a bug in my program that caused it to exit before closing the file).

Now some of my sqlite files have advisory locks that refuse to go away. I can restart mfsmaster or mfsmount and the advisory locks remain.

Here are select lines from strace:
```
open("/data/moosefs/cas-data/8e87", O_RDONLY|O_CLOEXEC) = 3
pread64(3, "SQLite format 3\0\20\0\2\2\0@  \0\0\0g\0\0\21\34"..., 100, 0) = 100
fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = -1 EAGAIN (Resource temporarily unavailable)
write(2, "Error: database is locked\n", 26Error: database is locked
```

These files are in the small megabytes. They are not opened on multiple machines, although the filesystem is mounted on multiple machines. I did have some hardware failures necessitating that I reboot the mfsmaster machine (which is also the mfsmount machine).

I have moved the wedged files to a temporary directory and then copied the files to the original place. Now my application works again.

I will keep the "locked" files. Please let me know how I can provide more information.

**Comment by oxide94** [comment]
Hi @njaard,
thanks for posting the issue.

As I understand, you encountered the issue after remounting MooseFS share (which was caused by some H/W issues and necessity of rebooting the machine). In general locks are assigned to sessions, so if a file is locked and the mount connection (session) is broken (e.g. MooseFS mountpoint is improperly unmounted), the lock still remains.

In such case you need to manually remove the session using `mfscli` or by clicking "click to remove" text next to the inactive session in "MOUNTS" tab.

Sessions mechanism in MooseFS is helpful e.g. when there are some network issues and connection is temporarily broken. After resuming the connection, `mfsmount` will connect with the same session number and everything will be working fine, but in your case, as the mountpoint was completely remounted, `mfsmount` got a new session number.

Let me know if something would be unclear, I will elaborate.

Thanks,

Best regards,
Peter / MooseFS Team

**Comment by oxide94** [comment]
Hi @njaard,

Yes, it is because some time passed since your issue. The inactive mounts' sessions are "remembered" by Master Server for 86400 seconds (i.e. one day) - this is the time Master Server waits for a reconnection. And if particular session haven't reconnected during this period, they are automatically removed (similarly as you would remove them by hand as I described earlier).

This parameter can be configured, so if you want, you can decrease this time in `mfsmaster.cfg`. See the following parameter:

```
SESSION_SUSTAIN_TIME
How long to sustain a disconnected client session (in seconds; default is 86400 = 1 day)
```

After changing it, do not forget to issue `mfsmaster reload` to let it reload the config file.

Best regards,
Peter / MooseFS Team

**Comment by njaard** [comment]
Thanks very much for your help.

I thought the files were still locked because I was the wrong user.
