### ISSUE TITLE
read only

### ISSUE THREAD

**Issue by xor256** [moosefs/moosefs#109]
Is possible to using this file from every web source?
For example:
1. I put image and steganography data inside it.
2. I put comment on web page
3. I put pastebin
I can use my local encrypted file and all up 3 data to read one binary file.
I can add by hand my mixed,encrypted data and using it as one file?

**Comment by oxide94** [comment]
Cześć Krzysztof @xor256,

I'm not sure what exactly you are asking about. In general MooseFS is a POSIX-compliant file system, so you can put any data you need as from user / application perspective it works as any other POSIX-compliant file system (like EXT4, XFS, ...).

You can write us directly at support@moosefs.com in order to get help, even in Polish.

---

Nie jestem pewien, co dokładnie masz na myśli. Generalnie MooseFS jest systemem plików zgodnym z POSIX-em, także możesz go używać do przechowywania dowolnych danych, a z poziomu aplikacji (czy też użytkownika) są one widoczne jak dane na każdym innym systemie plików zgodnym z POSIX-em (np. EXT4, XFS, itd.).

Jeżeli chcesz porozmawiać z nami po polsku, możesz napisać na support@moosefs.com.

Best regards / Pozdrawiam
Peter / MooseFS Team

**Comment by xor256** [comment]
Na razie dostałem bilet i obietnicę odpowiedzi ;-) Napiszę więc też tutaj skoro juz się zaczęło.

Szukałem i nie znalazłem systemu plików, ktory z jednej strony byłby oparty na publicznych zasobach, aby nie trzeba było się przejmować jakością hostingu z drugiej strony system oferujący dobry poziom szyfrowania. Myślę, że system ten mógłby być tylko do odczytu co wiązalo by się z tym, że zasoby trzeba by było zapisywać ręcznie. Ale jako przykład i koncept byłby użyteczny.

Wyobraźmy sobie, że mam program w C, który działa z linii komend i pozwala odczytać pliki (stworzyć na dysku) lub lepiej dwa programy, jeden jak obsługa archiwum plikowego (arj,rar,tgz) drugi jako fuse.

Jako zasoby uzywało by się wszelkich darmowych miejsc, gdzie można zostawić wiadomość. Od komentarza na stronie, pastebin, systemy udostępniania grafik/filmów  po lokalny cache. Jeślidodatkowo była by szansa nadmiarowości w danych (coś jak raid5) taki system byłby dość odporny na wszelkie błędy. 

Wystarczyło by tylko zainstalować jeden program i zawsze mielibyśmy własne pliki rozproszone na wielu serwisach, zaszyfrowane z lokalnym cache dla bezpieczeństwa (dla paranoików można by było przechowywać część danych zawsze na dysku lokalnym, w ten sposób nawet jesli by ktoś chciał nie mógłby odczytać danych ani z dysku ani z sieci, tylko połączenie obu tych 'zasobów' dało by poprawne dane).

Wspolczesne dyski niestety nie działają na każdym systemie, mają ograniczenia (tu potencjalnie nie było by dzych ograniczeń), a i możliwość dowolnego zaszyfrowania danych była by bardzo istotna dla wielu.
Taki system plików można by było używać z wielu miejsc i przez wiele osób.

**Comment by acid-maker** [comment]
I will write answer in polish, but to people who do not understand - this question in general is about using public storage (forums, dropboxes etc.) as "chunkservers". Nice idea but not for MooseFS - it should be something different.

And now polish ...

Generalnie bardzo ciekawy pomysł, ale zupełnie nienadający się do MooseFS'a. To zupełnie nie pasuje do filozofii pracy łosia - to zdecydowanie musiałby być zupełnie inny produkt. Jedyne co nam chodzi po głowie, to zrobienie styku do jakichś znanych chmur (typu Amazon) ale głównie po to aby można było sobie "awaryjnie" powiększyć przestrzeń korzystając z tego typu zasobów gdyż typowo są one droższe od własnych serwerów, a zatem nie bardzo się nadają na "główny" storage.

Na chwilę obecną nie bardzo mamy zasoby aby zaczynać tego typu projekt.
