### ISSUE TITLE
No 3.0 version on ppa

### ISSUE THREAD

**Issue by thjashin** [moosefs/moosefs#14]
Hi,

[http://ppa.moosefs.com/stable/apt/ubuntu/trusty/pool/main/m/moosefs/](http://ppa.moosefs.com/stable/apt/ubuntu/trusty/pool/main/m/moosefs/)
There seems to be no 3.0 version on the stable ppa, which caused my apt-get to fail.

**Comment by oxide94** [comment]
@thjashin 
Hi,

I posted about it on our mailing list - please find the full notification information (by the way - we encourage you to subscribe to the MooseFS-Users Mailing List): [https://sourceforge.net/p/moosefs/mailman/message/35150882/](url)

We had to rollback to MooseFS 2.0.89 in `stable`, because newer (3.0.x) MooseFS Clients are not able to "talk" with old (2.0.x) MooseFS Master Server (Client returns error: "incompatible Master version").

Actually there is no problem when you follow our guidelines from "Upgrade Guide" - I mean do the upgrade in supported order (1. Master Server, cli, cgi, cgiserv, 2. Metaloggers, 3. Chunkservers, 4. Clients / Mounts - they should be upgraded at the end).

Of course 2.0.x Clients can connect to 3.0.x Master Server.

The resolution is just to change `stable` to `moosefs-3`, so full URL would be (basing on your example): [http://ppa.moosefs.com/moosefs-3/apt/ubuntu/trusty/pool/main/m/moosefs/](url). This information will be posted on our website today.

Regards,
Peter

**Comment by oxide94** [comment]
I'm posting the full message here, for other Users:

> Dear MooseFS Users,
> 
> we'd like to inform you, that we decided to change our repository structure.
> (examples based on Ubuntu 14.04)
> 
> 
> 
> deb http://ppa.moosefs.com/stable/apt/ubuntu/trusty trusty main
> 
> "stable" in the entry above now points to the latest stable MooseFS from 2.0 branch (at this moment - 2.0.89).
> *This behaviour will be kept until end of July 2016*
> 
> *Starting from August 1, 2016, "stable" in the entry above will point to the latest stable MooseFS from 3.0 branch (at this moment - 3.0.77)*
> 
> "stable" symlink is going to be removed at December 31, 2016 - this method will **NOT** work after this date.
> 
> 
> 
> Starting from today, it is also possible to use the following entries, so you can switch your repositories consciously either to MooseFS 2 or MooseFS 3 (***we recommend reconfigure your repos before mentioned end of July 2016***):
> 
> deb http://ppa.moosefs.com/moosefs-3/apt/ubuntu/trusty trusty main
> --> this entry points to the newest stable MooseFS 3.0.x version (3.0.77 at the time of writing this e-mail)
> 
> deb http://ppa.moosefs.com/moosefs-2/apt/ubuntu/trusty trusty main
> --> this entry points to the newest stable MooseFS 2.0.x version (2.0.89 at the time of writing this e-mail)
> 
> 
> 
> Of course it is still possible to use "version control" in the repository URL, i.e. version number instead of "stable", "moosefs-3" or "moosefs-2":
> 
> deb http://ppa.moosefs.com/3.0.77/apt/ubuntu/trusty trusty main
> 
> --> the entry above will still work and at the moment we don't plan to change it.
> 
> 
> 
> This information will be published on our website soon.
> 
> In case of any questions, please don't hesitate to ask! :)
> 
> 
> Best regards,
> Peter from MooseFS Team
> 
> -- 
> Piotr Robert Konopelko
> MooseFS Technical Support Engineer | moosefs.com

Peter

**Comment by thjashin** [comment]
I've changed to moosefs-3 and everything worked fine. Thanks!

Best,
Jiaxin
