### ISSUE TITLE
missing release tags for v3.0.102 and v3.0.103

### ISSUE THREAD

**Issue by borkd** [moosefs/moosefs#155]
v3.0.102 and v3.0.103 cannot be found in https://github.com/moosefs/moosefs/releases. Neither tag is present in cloned repo

**Comment by oxide94** [comment]
Hi @borkd,

MooseFS v. 3.0.102 will not be released, but we have just released and tagged v. 3.0.103. The tag couldn't be found earlier, because we wanted to add [a few more commits](https://github.com/moosefs/moosefs/commits/master) which fix compatibility issue with Python 3 and improper disconnection of Chunkservers from Master during Chunkserver reload.

Also in the mean time we were able to finish tests of new `mfsmetadirinfo` tool, so it is also a part of the release. You can read more about this tool and other new features and fixes in `man mfsmetadirinfo` and [release notes](https://github.com/moosefs/moosefs/releases/tag/v3.0.103).

Thanks,
Peter / MooseFS Team
