### ISSUE TITLE
Moosefs loses data when a drive is full

### ISSUE THREAD

**Issue by njaard** [moosefs/moosefs#160]
When any *one* of the storage devices gets full (`ENOSPC`) and moosefs decides to store a chunk there, the chunk doesn't get stored, and then the chunk is lost, even if the the goal for that file is 2.

What's more is that there are plenty of other chunkservers that have plenty of available space, so I can't tell why moosefs is choosing the one that's closest to capacity (I don't have any special storage classes). However, The full server has fewer drives and they're smaller.

**Comment by xandrus** [comment]
Hi,
This is the latest MooseFS 3.0.103 version?

For me, it looks like goal 1, not goal 2.
I will take a closer look but we have to be sure that this file is in goal2.

**Comment by njaard** [comment]
Yes, it is absolutely 3.0.103, except for possibly mfsmount.

It may have been goal 1 at the time I ran mfsfileinfo for the above, because I needed to free up space quickly. At the time the error occurred, I am certain it was goal 2.

**Comment by borkd** [comment]
@njaard - while goal/storage class change commands return in an instant, the replications/deletions needed to effect that change may take arbitrarily long periods of time, depending of multitude of factors. With that said, goal may have been already set to 2, but only one chunk may have existed at the time the write operation was issued. In general, specifying a goal of 1 means you, the user/operator are OK with the risk of bad things(TM) happening to such files should a failure strike.

@xandrus - what could be improved, for the benefit of better documentation and usability:

- revisit default space limits with todays disks and backend filesystems in mind
- add a "PARANOIA" flag, which would turn parse errors into hard fails
  https://github.com/moosefs/moosefs/blob/1dfc5f18659e004a0d9950629485ddf078f4fc2a/mfschunkserver/hddspacemgr.c#L6401 and https://github.com/moosefs/moosefs/blob/1dfc5f18659e004a0d9950629485ddf078f4fc2a/mfschunkserver/hddspacemgr.c#L6407  or when a properly formatted but mistyped limit makes little sense: 
https://github.com/moosefs/moosefs/blob/1dfc5f18659e004a0d9950629485ddf078f4fc2a/mfschunkserver/hddspacemgr.c#L6467 or https://github.com/moosefs/moosefs/blob/1dfc5f18659e004a0d9950629485ddf078f4fc2a/mfsmaster/matocsserv.c#L2819

- Document what happens when a sparsely written chunk grows in size over time, and at some point either hits an I/O ERROR, ENOSPC, or SPACE LIMIT set by administrator in `mfshdd.cfg` file. Let's assume two scenarios: in one there exist other chunkservers with adequate labels and free space, and one in which there is no space available for set labels and STRICT mode is in use.

**Comment by njaard** [comment]
@borkd, I think you misunderstand. The goal was 2.

**Comment by borkd** [comment]
Racing with _any filesystem_ which is running out of space is rarely a pleasant experience. You have decided to not provide information about underlying infrastructure (from the new issue template), and this could help shine some light on how to reproduce the problem you experienced. Considering adding more details.

When space gets really tight rebalancing, replications and deletions may not complete fast enough to complete before for your client-side retry limit. 

By downgrading to 1, for whatever reason, you can make a bad situation even worse. That is all

> Yes, it is absolutely 3.0.103, except for possibly mfsmount.
>
>  It may have been goal 1 at the time I ran mfsfileinfo for the above, because I needed to free up space quickly. At the time the error occurred, I am certain it was goal 2.

**Comment by borkd** [comment]
v3.0.103, (commit https://github.com/moosefs/moosefs/commit/632b26c16ffd0e23ce0986ea9b1cbd946468d211), offers RESERVE_SPACE - Set amount of space reserved for superuser (default is 0 = do not reserve space for superuser - see NOTES). Related issue #133
