### ISSUE TITLE
GCI: please port to Python3; Python2 is deprecated

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#181]
Python 2.x is deprecated and will not be maintained upstream past 2020.

Please port CGI to Python3.

Initial conversion could be done by `2to3` utility and then hopefully only few things will have to be fixed by hand.

**Comment by acid-maker** [comment]
Python 3 is supported properly since version 2.0 (as I remember).

BTW. `2to3` utility can change only very basic things. Lot of fixes were needed, but they are there. Our mfscli/mfscgi is compatible with python 2 and python 3.

This is why we use `#!/usr/bin/env python` in shebang - not 'python2' nor 'python3'. The only problem is that sometimes there is only python 3 installed and name 'python' is not linked to it.

**Comment by onlyjob** [comment]
Excellent, thanks.

When Python2 and Python3 are installed together `configure` script defaults to python2 so generated shebangs were pointing to old `/usr/bin/python`.

With little hint through `export PYTHON=/usr/bin/python3`, `configure` used Python3 and cgi/cgiserv seems to work.

Please close this ticket if there is nothing left to do for python2-->python3 transition. Thanks.
