### ISSUE TITLE
chunkserver: bad resilience to crc error

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#192]
One chunk failed CRC test:

~~~~
test_chunk: file:/var/lib/mfs/hdd02/xfs/00/chunk_000000000007057B_00000001.mfs - crc error
~~~~

That triggered race/flood of the following messages in log:

~~~~
move_chunk: file:/var/lib/mfs/hdd02/xfs/00/chunk_000000000007057B_00000001.mfs - crc error
~~~~

logged at least 26 time per second for _hours_ flooding logs...

I recommend to remove chunks that failed CRC test right away. Thay are not good for anything and removing would prevent issues like this one.

**Comment by oszafraniec** [comment]
Don't remove chunks only because of CRC errors as they can still contain valid data. This is a bad idea. See issue #106 as an example.

**Comment by onlyjob** [comment]
If chunk failed CRC check then it contains garbage. There are no reasons to keep garbage.
LizardFS have a correct behaviour in that regards and it flawlessly passed most vigorous data corruption tests that I ever did. 

At very least it could be made configurable but even if configurable it is not cool for chunkserver to fail on one corrupted chunk.

**Comment by acid-maker** [comment]
Chunkserver doesn't fail on corrupted chunk - only reports it to syslog and also to master. Master then flags this copy as 'invalid' and no longer use it in I/O. This is correct behaviour - not deleting everything - maybe for lizards it is ok to delete crucial data everytime something goes wrong, but do not tell me that this is "correct behaviour".

**Comment by onlyjob** [comment]
I have to insist that removing chunk identified as corrupted is the correct behaviour.

Don't you trust CRC check? Do you expect admin to manually delete all corrupted chunks, as soon as they are detected to prevent logs from flooding?

Here we have a legitimate problem: recoverable situation without automatic action and endless continuous logging demanding admin interaction...

Chunk that failed CRC check can not contain "crucial data". It is just an invalid chunk and it's best to recycle it rather than let it stay around.

**Comment by acid-maker** [comment]
But chunks with wrong CRC are finally deleted, but only when there are valid copies. Our algorithm:

1. CRC error is reported to master
2. master flags this copy as invalid copy (formally 'copy with wrong CRC')
3. master tries to fulfill goal (i.e. make replication using another copy)
4. if goal is fulfilled (replication from '3' succeded) then chunk with wrong CRC is deleted

As you see when we are able to fulfill goal without corrupted chunk (almost 100% of all cases) then of course we don't keep corrupted chunks. We keep such chunks only if all copies happend to be incorrect. In such case it is better to keep them and let administrator to find the best copy. In the future we plan to add special tool for this, but as for now you need to do it manually - still better than lost all your data - especially considering that usually is the checksum that is wrong and not the data.

To stop such messages I can add special flag in chunkserver that will prevent future checks, because I agree that one message is more than enough in such case, but we will keep such chunk as long as master want to have it there.

**Comment by onlyjob** [comment]
This is not the behaviour I observed. Invalid chunk was one of two, on strict storage class. There were no missing chunks reported and (as far as I can tell) all files were readable. Yet message was logged repeatedly for hours and corrupted chunk was not removed when it _should have been deleted automatically_.

**Comment by onlyjob** [comment]
Perhaps it is a good idea to avoid re-testing corrupted chunk...
IMHO the best way to avoid re-testing it would be to remove it.
Is there any scenario when it might be useful to save corrupted chunk? I can't think of any hypothetical reason whatsoever -- not even when RAM is corrupted...

**Comment by jkiebzak** [comment]
or, why not prioritize fulfilling the goal?

**Comment by onlyjob** [comment]
> or, why not prioritize fulfilling the goal?

Indeed. Corrupted chunk means undergoal or endangered file...
And of course trying to move corrupted chunk makes no sense at all...
