### ISSUE TITLE
mfschunkserver[27467]: about 1770 seconds passed and lock still exists

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#196]
I  an run   /usr/local/mfs/sbin/mfschunkserver restart , but still not stop, and system log print "mfschunkserver[27467]: about 1770 seconds passed and lock still exists"

**Comment by xandrus** [comment]
Hi,
Would you be so kind and tell us which version you use?

Also, please attach system log from this chunkserver.

**Comment by zhs077** [comment]
> Hi,
> Would you be so kind and tell us which version you use?
> 
> Also, please attach system log from this chunkserver.

mfs-chunkserver-2.0.71

**Comment by oxide94** [comment]
Hello @zhs077,

This version is very old – it [was released almost 3 years ago](https://github.com/moosefs/moosefs/releases/tag/v2.0.77) and it is not supported nor maintained / bugfixed anymore as MooseFS 2.x support ended on Dec 31, 2017. Even if the issue you encountered is a bug, it is extremely tough to track it in this version – especially that it may have already been fixed in newer versions, either 2.x or 3.x.

We strongly recommend upgrading your cluster to the latest stable and supported version, i.e. 3.0.103. This version (and MooseFS 3.x in general) has many improvements and bug fixes comparing to MooseFS 2.x. If the issue persists after the upgrade, do not hesitate to open a new issue here on GitHub.

You may find more information on support status of various MooseFS' versions [here](https://moosefs.com/support/#moosefs-support-status).

Best,
Piotr
