### ISSUE TITLE
MAINTENANCE BUG

### ISSUE THREAD

**Issue by yinjiawind** [moosefs/moosefs#23]
Hi,
I found a bug with maintenance mode. My MooseFS version is in 3.0.84. 
If I shutdown a chunkserver A  with maintenance mode on, the chunk under this chunkserver will not be replication.Then, I shutdown another chunkserver B with maintenance mode off, I found that the chunk under chunkserver A will be replication.
The reason on this bug is that step 9 in mfsmaster/chunks.c::chunk_do_jobs(). if disconnected_server is not equal disconnected_server_in_maintenance, will replicate chunks that under the goal. 
I think this bug influence all the version of MooseFS that have maintenance mode.I hope you can understand what I mean. Because My english is not good :)

**Comment by oxide94** [comment]
Hi @yinjiawind,
> I hope you can understand what I mean. Because My english is not good :)

Don't worry! :)

> If I shutdown a chunkserver A with maintenance mode on, the chunk under this chunkserver will not be replication.Then, I shutdown another chunkserver B with maintenance mode off, I found that the chunk under chunkserver A will be replication.

It is like that by design - this is a feature, not a bug. It is well-described / documented in "**MooseFS 3.0 User's Manual**", paragraph **5.3 "Maintenance mode"**. You can get this manual from the following website: https://moosefs.com/documentation/moosefs-3-0.html.

Please take a look at the quotation (from the manual I mentioned above). It is in bold in the documentation:

> **Note: Server(s) in maintenance mode must match currently off (disconnected) servers. If they don’t match, all chunks are replicated.**

If you have any questions, please don't hesitate to ask!

Best regards,
Peter / MooseFS Team

**Comment by yinjiawind** [comment]
Thank you!
