### ISSUE TITLE
"mfsmaster -a" should have been a utility

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#239]
Promoting metalogger's data to master is needlessly difficult because master should be started with `-a` option exactly once to convert `_ml` files.  
Metalogger data conversion should have been implemented as a command line utility because master is typically started by init system (e.g. systemd) and administrator must insert and then remember to remove `-a` parameter from init script or `.service` file.

**Comment by oxide94** [comment]
It was like this earlier (in MooseFS 1.x for sure). There was a tool called `mfsmetarestore` (see an old manpage cached somewhere on the internet [here](https://linux.die.net/man/8/mfsmetarestore)) which did exactly what you mention.

However consider the following:

In general we **do not** recommend to set up the autostart of Master Server and we do recommend to manage it manually (`mfsmaster start` or `mfsmaster -c /etc/mfs/mfsmaster-instanceName.cfg start`, `mfsmaster stop`, `mfsmaster reload`, `mfsmaster -a`). Why? Because there are only several certain cases when Master Server is not running and in every such case it needs an engagement of the admin and a manual action:

1. OS upgrade / MooseFS upgrade: needs to stop the Master Server and start (+ sometimes rebooting the machine). Issuing `mfsmaster stop` and `mfsmaster start` is not a problem. Also when you upgrade the package it is recommended to stop the Master Server, backup `/var/lib/mfs` (or at least `/var/lib/mfs/metadata.mfs`), update the package, start Master Server. Following blind automation in case of such (how crucial!) services as Master Server is just jeopardising your system to potential issues.
2. Power failure: When the machine boots up after a powercut, Master will not start automatically anyway, because it will not be able to find a properly dumped `metadata.mfs` file (which is saved (almost) only during `mfsmaster stop`). And what is more important: Admin may want to **make a full backup** of `/var/lib/mfs` and `/etc/mfs` before performing **any** actions (and this is very recommended). So after making the backup (which in case of power failure is done manually), issuing one extra `mfsmaster -a start` is not a problem
3. Moving the Master Server to new machine: see point 1

I think there is one or two more exceptions which could be added to the list above but it went out of my mind at this very moment. I will update this list when I remember. The most important are above. Anyway – in any other case Master Server just runs for months, years, ... without stop.

**Comment by onlyjob** [comment]
No, no it is all wrong... It is fair that manual action is required in case of master failure. For example primary master is down and we do no know if it is safe to restart (e.g. suspected data corruption, etc.).
Let's take healthy metalogger and promote it into master. It should not be difficult but in reality a very precise sequence of steps should be followed in order for it to succeed.
Do you trust yourself to do it safely at 3am in the morning being tired and under stress, without recent rehearsal/training? It should be scriptable. But currently it is difficult: even after successful conversion of metalogger data, master started with `-a` option leaves original metalogger files in place so accidental start with `-a` option again wipes current metadata without warning. This is a planted time bomb with a tripwire to endanger a sensitive operation beyond reason. Your assumptions on manual startup are wrong too. Do you reboot-test your systems? What if reboot happens while you are on leave and temporary staff have never performed manual start of master let alone promotion of metalogger to master? Service file to start master is useful as one can not rely on manual start forever. Once master successfully started from metalogger data, it should be possible to restart it safely _without any modifications to service file_.
Currently one has to 

  1. copy metalogger files
  2. start master once with `-a`
  3. stop master
  4. remove metalogger files
  5. start master normally

(1 and 4 may be optional when master and metalogger share the same `DATA_PATH`)

Steps 1,2,3,4 should be easily and safely scriptable without intermediate start of `mfsmaster`. Therefore `-a` does not belong to `mfsmaster`. Current behaviour is illogical and unsafe. It is just silly that one needs to start master once to prepare it for normal operation in situation when metadata is obtained from metalogger.

---

Also, presence of redundant service management functionality and PID files management is disturbing. This design needlessly duplicates init system functionality and not in the most correct way.
See https://github.com/lizardfs/lizardfs/issues/218 for discussion.

**Comment by asyslinux** [comment]
Interesting, but in case of use PRO version of MooseFS. Where we have for example 1 Leader and 2,3,4 Follower servers, without using metaloggers. If all servers have power failure at one moment(including dump time), -a option can restore metadata from changelogs , not _ml changelogs? Or in this case we can only use for repair metadata.back file?

**Comment by pkonopelko** [comment]
Option `restore` to `mfsmaster` has been added in commit bb596ff, therefore now you can use

```
mfsmaster restore
```

in order to recover metadata file and exit. `restore` tries to restore metadata file using backup metadata files and changelogs; if successful it will store recovered metadata file end stop, it will never start master process.
