### ISSUE TITLE
performance [question]

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#251]
Hi,

Could someone explain moosefs performance to me?

My cluster has decent performance when I simply write a bunch of data to it or read from it.
So basically it is ideal backup storage for my photos, especially with snapshot feature.

but
When I try to use moosefs mount more "operationally"
e.g. as a data store for LightroomCC, it's excruciatingly slow.
indexing photos from moosefs, or any conversion operations are just killing me.

The Lightroom catalogue sits on my local SD so that's not a problem
I am also using moosefs 3.0.104 on mac osx 10.13.6
Lightroom Classic CC 8.2

**Comment by acid-maker** [comment]
MFS is a network filesystem, so sequential operations like copying to/from can be gratly optimized using read-aheads, write-back caches etc, but with random file access your network latency will significantly slow down your I/O.

**Comment by eleaner** [comment]
thank you
that makes sense
is it possible to use mfs with some kind of local cache?

**Comment by acid-maker** [comment]
Mfsmount has a lot of caches in memory. The problem is that for random access (especially random read) each time mount has to receive only requested part of file via network. This part of requested file of course stays in cache for a moment, but then usually is requested different part of the file, so mounts has to receive it separatelly.

In your case likely the solutikon would be to download whole files (in this case photos), store them temporarly on local harddrive and then update local changes in MFS - in general not easy to implement.

BTW. You can check what kind of operations are performed during indexing photos. There is "hidden" file `.oplog` you can 'read' to 'see' what is happening on your filesystem. In "Terminal.app" you can run command `sudo cat /mnt/mfs/.oplog | tee mfslog.txt"` (or something like this). You will be able to check what kind of operations are there - maybe problem lies not in reading files but other operations - like lookup, readdir or even something else.

**Comment by eleaner** [comment]
Currently, I am using moose as photo-store for my lightroom library
backed up by SSD storage for the library itself and cache
It's pretty usable
I am closing the topic
