### ISSUE TITLE
Recovering from Unclean master shutdown.

### ISSUE THREAD

**Issue by dragon2611** [moosefs/moosefs#278]
Hopefully a quick one, What's the better way of recovering from an unclean master shutdown? (In this case apparently caused by a Motherboard failure.)

Should I just be running mfsmaster -a (assuming I get the data from the original dead server, the dc staff are going to try putting the drives in another server with the same model of controller.etc)

Or should I be copying the data from one of the metaloggers (Or even promoting one in place, although I don't really want the master where I currently have a metalogger).

Last time that machine crashed I just ran mfsmaster -a which worked but corrupted a few files because any metadata that hadn't dumped to disk was lost.  If I understand correctly the meta-loggers actually get metadata updates all the time rather than just when the perodic snapshot/save to disc occurs so what I did last time was probably wrong and what I really should be doing is getting the data from the metalogger since it's likely to be just a few seconds behind the master if that?

**Comment by acid-maker** [comment]
Metalogger receives all changes online, so usually files that are stored there are more recent than those on a broken master server. Because of that after master crash it is a good idea to copy all files from mfsmetalogger to mfsmaster and then run 'mfsmaster -a'. Mfsmaster will automatically use the most recent files. Usually it is enough to just copy latest changelog file (or two files) from the metalogger ('changelog_ml.0.mfs',changelog_ml.1.mfs) to folder where mfsmaster changelogs are stored (typically '/var/lib/mfs/'). You don't need to change those files' names.

**Comment by dragon2611** [comment]
Thanks it recovered cleanly from the metalogger data 👍
