### ISSUE TITLE
what does it mean "long loop detected" [question]

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#282]
I noticed messages like

`long loop detected (8.561387s)`

what does it mean?

**Comment by acid-maker** [comment]
It basicly means that your mfs process spent n seconds (n > 5.0) doing "something". This "something" may cause network timeouts etc. We need to track down all such situations. This message is left mainly for debug purpouses. Currently the only known occurence is caused by hangs in the kernel during data writing.

**Comment by oszafraniec** [comment]
FYI, I see this only if we delete tons of files from MFS. We can write to it and read from it without any limits (high backup traffic every night), but the moment we delete a lot of files (I mean thousands or millions)... this happens over and over again.
```
Jun 23 08:31:05 mfs-chunk-002 mfschunkserver[2324]: long loop detected (12.763647s)
Jun 23 08:31:05 mfs-chunk-002 mfschunkserver[2324]: masterconn: connection timed out
Jun 23 08:31:05 mfs-chunk-002 mfschunkserver[2324]: closing connection with master
Jun 23 08:31:07 mfs-chunk-002 mfschunkserver[2324]: connecting ...
Jun 23 08:31:07 mfs-chunk-002 mfschunkserver[2324]: connected to Master
```
I've already decreased DEL_LIMITs from defaults which helps, but not for long.
```
CHUNKS_SOFT_DEL_LIMIT = 4
CHUNKS_HARD_DEL_LIMIT = 10
```

This reconnecting is really annoying 👎 

<img width="327" alt="Zrzut ekranu 2022-06-23 o 08 33 14" src="https://user-images.githubusercontent.com/3938516/175231165-60bde8e9-0469-4bb5-a03a-0074f0a9ab09.png">

**Comment by chogata** [comment]
What kind of hard drives do you have, what filesystem on them? If the long loops happen only when deleting files, it means physical deleting of chunks from chunkservers' drives is the problem. From our observations: deleting a file is the worst possible operation in any filesystem. SSD drives are better than HDD, but not as much as one would expect sometimes. There are some things you can do to optimize that (another fs, newer kernel), but basically your best solution might be increasing the timeout.

There is literally nothing we can do once a process/thread "hangs" on a kernel operation - this is totally uninterruptible. The only thing is to try to change something in the environment so the hangs do not happen or do not last that long or do not cause disconnections (hence timeout settings).

**Comment by oszafraniec** [comment]
@chogata first of all, I don't complain about MFS, it's a great peace of software. I just run into "long loop detected" problem from time to time and wanted to leave some comment about it and that some can play with DEL_LIMIT variables if the cluster keeps disconnecting chunkservers on high delete load, like in my case ;)

If information below will be usefull... i'm happy. I don't seek help, but maybe you will have some hints ;) 

Hardware per chunkserver: Supermicro chassis/MB/etc; 36x IronWolf 8TB; Intel(R) Xeon(R) CPU E3-1220 v6 @ 3.00GHz; 32GB RAM; Avago HBA; 10G Intel network cards

Filesystem is XFS mounted like this:
`/dev/sdac1 on /moose/030 type xfs (rw,noatime,nodiratime,swalloc,attr2,largeio,nobarrier,inode64,allocsize=64k,logbufs=8,logbsize=256k,noquota)`

MFS version is 3.0.116 @ Ubuntu 18 and 20 LTS, kernels etc upgraded last evening.
It's a cluster for backups and we are running it for a lot of time without problem.

I've made some testing plaing with DEL LIMIT and... take a look:
<img width="1103" alt="Zrzut ekranu 2022-06-23 o 11 43 16" src="https://user-images.githubusercontent.com/3938516/175272931-7ea58696-0031-4074-b33d-bcafab82fd42.png">

Here are the master stats, so you know what the cluster is doing. It's a cluster for backups only.

<img width="1432" alt="Zrzut ekranu 2022-06-23 o 11 57 26" src="https://user-images.githubusercontent.com/3938516/175273107-ebc2daa8-b973-420c-a862-ce64a6532b4d.png">
<img width="1430" alt="Zrzut ekranu 2022-06-23 o 11 57 37" src="https://user-images.githubusercontent.com/3938516/175273129-f8e6d77f-4806-4b69-9768-bd1465401fd1.png">
<img width="1431" alt="Zrzut ekranu 2022-06-23 o 11 57 46" src="https://user-images.githubusercontent.com/3938516/175273138-917a8a63-4682-442b-aa27-09286b07124c.png">
<img width="1434" alt="Zrzut ekranu 2022-06-23 o 11 57 56" src="https://user-images.githubusercontent.com/3938516/175273154-7eb7569c-2004-4366-bd58-fbc67786affd.png">
<img width="1431" alt="Zrzut ekranu 2022-06-23 o 11 58 18" src="https://user-images.githubusercontent.com/3938516/175273160-39a16b29-8571-4568-88e9-09232dd6a207.png">

**Comment by chogata** [comment]
@oszafraniec I know you like MooseFS, but you said that the disconnections are really annoying, so I wanted to see is there is something to be done in your particular case to not have them after all :)

If longer reaction time in case of one server's malfunction doesn't bother you much, I would play with timeout settings, i.e. I would keep higher deletion limits and increase timeouts (20 or maybe even 30 seconds instead of 10) to see if maybe chunkservers stop disconnecting so often.

As I wrote before - deleting is the worst operation for a regular, "local" filesystem. I don't know why, exactly, this is not a scientific thesis, this is simply our observation made during many, many tests. You have mechanical hard drives, high quality ones, but still, mechanical. On such drives, every N-th delete operation, if they are done in sequence, takes exponentially longer than average. The solution is, of course, to lower deletion limits so that the operations stop being sequential, but that means if you delete a lot of files at the same time, it takes a looong time for MooseFS to get rid of unneeded chunks. If that's not a problem, then lowering the deletion limits is the solution. If that starts to be a problem, then maybe the solution with longer timeouts could help.

And, while xfs is a great filesystem in general and we still recommend it for chunkservers as the filesystem that is "overall the best", it can be sometimes really slow with deletions. Ext4 is better with that (but worse with other i/o, so...)

There is no perfect solution when it comes to deleting files. For some reason it's the toughest operation for local filesystem, which has its consequences for MooseFS too. Any other long loop occurrences can be blamed either on malfunctioning hardware or on issues with code (which we are always happy to hunt down and fix). Deletion long loop is something that sometimes cannot be avoided.

In case somebody wants to ask the question: _BUT chunkserver is multithreaded, WHY one thread hanging on a delete operation would cause a network timeout in the main process_? Well, the short answer is: it should not happen in theory, but in does in practice ;) Our theory is that if several disk operations hang in kernel, kernel ITSELF hangs for long enough that it doesn't schedule enough run time for other processes, including chunkserver's main process. Linux is not RTOS. And nothing else will help in this scenario, only longer timeouts.

**Comment by oszafraniec** [comment]
@chogata thank you... found MATOCS_TIMEOUT in master config and will play with it a little like you suggested ;) I've increased it to 20s and soft/hard DEL_LIMIT to 4 and 10 again... will see if it will work OK.

**Comment by oszafraniec** [comment]
@chogata just to let you know... yesterday evening i've updated 2 chunkservers from ubuntu 18 LTS to 20 LTS... don't know what to say, a picture speek's better

syslog is clean, now long loops, everything runs smoothly on DEL_LIMIT set to 8/20 and I consider to got back to defaults 👍 

<img width="1104" alt="Zrzut ekranu 2022-06-24 o 10 50 38" src="https://user-images.githubusercontent.com/3938516/175500179-58f10e4c-900e-406b-b7d4-3fb83f2f203a.png">

**Comment by chogata** [comment]
Told you, kernel ;)
