### ISSUE TITLE
 How to solve " can't find metadata.mfs - try using option '-a' "

### ISSUE THREAD

**Issue by GYUMO** [moosefs/moosefs#286]
# Can't  start master server rightly
Recently , when I came across the power cut add I cant' rightly shutdown my server and moosefs sysetm.Today when I want to restart my moosefs sysetm, I meet a problem.
![image](https://user-images.githubusercontent.com/17978899/63162740-ee0b9380-c055-11e9-9f90-205b07b0e222.png)
I take a look at the **/var/lib/mfs**, and just found ' metadata.mfs.back', ' metadata.mfs.back
.1', and I don't know  the difference between two files. 
So, how can I finish that problem to protect my data,thanks!

**Comment by acid-maker** [comment]
You should do exactly what it suggest - run your mfsmaster with option '-a':

`mfsmaster -a start`

This has to be done manually - systemd scripts can't do that. If you are absolutely certain that nothing has changed since last metadata write you can just rename your file 'metadata.mfs.back' to 'metadata.mfs' - master will start using this file but will no apply any changes from changelog files.

I can add to master special 'restore' mode in the future. I think that someone once suggested this - in such situation it might be more convenient (especially when you want to start everything using systemd/sysv scripts)

**Comment by dragon2611** [comment]
@acid-maker It would be good if Master could wait for metaloggers on a startup from an  unclean shutdown to see if they're more upto date than the local storage.

**Comment by oxide94** [comment]
Hello @dragon2611,

> I take a look at the /var/lib/mfs, and just found ' metadata.mfs.back', ' metadata.mfs.back.1', and I don't know the difference between two files.

When Master Server is stopped gracefully, it dumps `metadata.mfs` file. When it is running, it dump whole metadata file every hour and saves it to `metadata.mfs.back*` files (and also rotates them every hour), so they contain a state of metadata as of `mtime` of the metadata dump. Number of these files kept in `/var/lib/mfs` depends on `BACK_META_KEEP_PREVIOUS` variable, configurable in `/etc/mfs/mfsmaster.cfg`:

```
# number of previous metadata files to be kept (default is 1)
# BACK_META_KEEP_PREVIOUS = 1
```

So if you have default value, you will only have `metadata.mfs.back` and `metadata.mfs.back.1`. Increasing this value increases number of metadata backups kept from previous dumps.

As your Master Server was stopped by a power cut and `mfsmaster` process was closed not in a graceful way, you should use `mfsmaster -a` in order to recover metadata from `metadata.mfs.back` and available changelogs, as @acid-maker advised.

Best regards,
Piotr / MooseFS Team

**Comment by dragon2611** [comment]
@oxide94 I think you meant @GYUMO, I was just suggesting a feature to automate/semi-automate the recovery from metaloggers in the event of unclean shutdown.

Also presumably if a metalogger was available and unaffected by the power loss (I.e it was elsewhere) it's worth copying the changelogs from it before doing the mfsmaster -a as they may be more up2date?

**Comment by oxide94** [comment]
Hello @dragon2611,

> @oxide94 I think you meant @GYUMO, I was just suggesting a feature to automate/semi-automate the recovery from metaloggers in the event of unclean shutdown.

Of course, I meant @GYUMO, I'm sorry.

> Also presumably if a metalogger was available and unaffected by the power loss (I.e it was elsewhere) it's worth copying the changelogs from it before doing the mfsmaster -a as they may be more up2date?

Yes, in such case it is worth copying the changelogs from Metalogger to Master Server. There is no necessity to rename them do do any actions – just copy to Master Server and it will handle them, as @acid-maker mentioned here: https://github.com/moosefs/moosefs/issues/278#issuecomment-515407353.

Thank you,

Best regards,
Piotr / MooseFS Team

**Comment by dianshane** [comment]
hello, having the same issue using your docker image ( moosefs/master) 
what is the fix for that?
