### ISSUE TITLE
[question] comparison to ceph

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#293]
Hello

Could someone put together a few sentences comparing moosefs versions to ceph?

as far as I can say:
- moosefs seems to be much easier to install and manage (personal opinion)
- moosefs work better with high latency
- moosefs seems to have lower memory requirements
- Ceph has ha and ec and is not limited to 8.2+ (for free)
- Ceph community seems to be much bigger and development really goes forward fast (e.g. deduplication to be available soon)

am I wrong? anything else?

I am talking from a perspective of a home cluster (say three machines, 12 HDD tops), less than 100TB

**Comment by onlyjob** [comment]
The most important thing about distributed storage system is integrity of data -- a something that was (and most certainly still is) _pathetic_ in Ceph. I could disqualify Ceph just based on simple fact that corrupted data reproducibly propagates all the way to the client without any warnings. When I was using Ceph few years ago it had _eventual inconsistency detection_ between storage nodes that tells you that data is corrupted _somewhere_. Go figure. I mean literally, "go figure" as there were no automatic repair and what they call "repair" is when random primary chunk (that may have been corrupted) is forcibly replicated to other nodes potentially destroying valid chunk(s). That is Ceph's manual repair for you when things go wrong.

Why this matters? You see, storage system is all about probabilities. What are the chances for one node to go down? Two? On large enough cluster low probability events become more common and even _mandatory_. Data corruption may be _perceived_ as rare event but on big cluster it is a certainty.

IMHO you are correct about almost everything except the last point regarding community and rate of development.

Ceph is not that much about community. Some years ago there was a big downtime of Sourceforge due to Ceph outage. RedHat representative commented on that something like "What did you expect? They were running unsupported community edition!". Informally RedHat people admitted that they only have few Ceph customers in Australia - not much for the entire country.

I'd go further and say that development of Ceph is its weakness because _complexity is the enemy of reliability_. Ceph code base is huge and bloat is enormous. It takes roughly an hour to build from source and produce 700+ MiB of binaries.
Project have strange priorities and when I was using Ceph I was troubled by "meh, whatever" attitude for very serious bug reports and there were many! I gave up after reporting around 50 issues and many of them were segfaults and other serious issues (e.g. time drift on one OSD wrecks the entire cluster; "poisoned" OSD knocks down the rest of them, etc.).

Ceph is not suitable for a small home cluster unless you want a full time job maintaining it.
Operationally MooseFS and LizardFS are much less demanding and more reliable than Ceph.

**Comment by marcomilano** [comment]
> Hello
> 
> Could someone put together a few sentences comparing moosefs versions to ceph?
> 
> as far as I can say:
> 
>     * moosefs seems to be much easier to install and manage (personal opinion)
> 
>     * moosefs work better with high latency
> 
>     * moosefs seems to have lower memory requirements
> 
>     * Ceph has ha and ec and is not limited to 8.2+ (for free)
> 
>     * Ceph community seems to be much bigger and development really goes forward fast (e.g. deduplication to be available soon)
> 
> 
> am I wrong? anything else?
> 
> I am talking from a perspective of a home cluster (say three machines, 12 HDD tops), less than 100TB

I agree.

All these points are correct. (Not only on small clusters but on large
clusters as well.)

Lack of built-in data integrity checks (end to end checksum checks) in ceph is also a big problem.
