### ISSUE TITLE
3.0.107/fuse3: Bonnie: drastic I/O error (rmdir): Operation not permitted

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#314]
When removing directories (git checkout) I've experienced an issue disturbingly resembling https://github.com/lizardfs/lizardfs/issues/662:

Reproducer is simple (as suggested in https://github.com/lizardfs/lizardfs/issues/662#issuecomment-524907828):
~~~~
$ /usr/sbin/bonnie++ -s 0 -n 1

Create files in sequential order...done.
Stat files in sequential order...done.
Delete files in sequential order...Bonnie: drastic I/O error (rmdir): Operation not permitted
Cleaning up test directory after error.
~~~~

IMHO issues that are so easy to test automatically should be found/exposed during pre-release testing.

**Comment by acid-maker** [comment]
Already fixed in c56310fd1d9f43f7b0894dbb12527dce5cd75414

This is simple mistake in packet size - has nothing to do with tons of bugs in lizard.

Passed automatic tests because it trigers only when inode number of your folder is bigger than 2^24, so you need for that system with more than 16 millions of files/directories. On small testing system it never triggers.

**Comment by onlyjob** [comment]
Very well, thanks. Good that was not too serious.

**Comment by onlyjob** [comment]
c56310f definitely helped. Thanks, @acid-maker.
