### ISSUE TITLE
Connection with chunkserver timed out (3.0.109)

### ISSUE THREAD

**Issue by IYEO** [moosefs/moosefs#319]
Hello everybody!

After update all MooseFS (non Pro) components from version 3.103 up to 3.109 I can't fully run MooseFS. It starts replication/synchronization and when replication almost has finished MFS Master losts connection with one (or more) chunkserver with message:
  _"connection with mfs_chunkserver_ip:port timed out"_.

By the way, chunkserver's service still working without any errors in logs.

After this event replication starts again. And so infinitely...

How to fix this problem? Could you help me with this question?

**Comment by IYEO** [comment]
Hello!

After a lot of time spent and having tried all possible options (including [best practies](https://moosefs.com/support/#best-practices)) we suppose that problem in our chunkservers that can not cope with the load (60 million of small files approximately). 
Some additional information.
Our chunkservers had located on virtual machines (LXC on QNAP NAS) at the time of my previous post. Now we have moved _almost_ all data from chunkservers on virtual machines to new chunkservers on "bare metal" (copy raw data from old chunkserver to new by _rsync_). Some chunks failed to copy to new hardware (rsync error). 
After start MooseFS on new chunkservers` hardware performance increased several times. But replication still can't finish (cycle):

- replication begins;
- errors appears on master`s log and chunkserver's log;
- replication stops after a while;
- replication begins;

Part of mfsmaster log:
```
Jan 13 10:30:22 gateway1 systemd[1]: Started MooseFS Master server.
Jan 13 10:31:34 gateway1 mfsmaster[16418]: csdb: found cs using ip:port and csid (192.168.12.121:9422,3)
Jan 13 10:31:34 gateway1 mfsmaster[16418]: chunkserver register begin (packet version: 6) - ip: 192.168.12.121 / port: 9422, usedspace: 0 (0.00 GiB), totalspace: 0 (0.00 GiB)
Jan 13 10:31:34 gateway1 mfsmaster[16418]: chunkserver register end (packet version: 6) - ip: 192.168.12.121 / port: 9422
Jan 13 10:32:02 gateway1 mfsmaster[16418]: csdb: found cs using ip:port and csid (192.168.12.122:9422,4)
Jan 13 10:32:02 gateway1 mfsmaster[16418]: chunkserver register begin (packet version: 6) - ip: 192.168.12.122 / port: 9422, usedspace: 0 (0.00 GiB), totalspace: 0 (0.00 GiB)
Jan 13 10:32:02 gateway1 mfsmaster[16418]: chunkserver register end (packet version: 6) - ip: 192.168.12.122 / port: 9422
Jan 13 10:32:10 gateway1 mfsmaster[16418]: csdb: found cs using ip:port and csid (192.168.12.123:9422,6)
Jan 13 10:32:10 gateway1 mfsmaster[16418]: chunkserver register begin (packet version: 6) - ip: 192.168.12.123 / port: 9422, usedspace: 0 (0.00 GiB), totalspace: 0 (0.00 GiB)
Jan 13 10:32:10 gateway1 mfsmaster[16418]: chunkserver register end (packet version: 6) - ip: 192.168.12.123 / port: 9422
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.122:9422) chunk: 0000000003181C37 replication status: Can't connect
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.122:9422) chunk: 0000000000C1F6DF replication status: Can't connect
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.122:9422) chunk: 000000000262C3B9 replication status: Can't connect
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.122:9422) chunk: 000000000355E8A9 replication status: Can't connect
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.122:9422) chunk: 00000000019BBCEF replication status: Can't connect
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.122:9422) chunk: 00000000006AE15D replication status: Can't connect
Jan 13 10:53:43 gateway1 mfsmaster[16418]: (192.168.12.123:9422 -> 192.168.12.121:9422) chunk: 0000000002CB610A replication status: Can't connect


```

Part of chunkserver (192.168.12.122) log:
```
Jan 13 10:49:12 mfschunksrv2backup mfschunkserver[25585]: scanning folder /mfs-volume/: 97% (1032s)
Jan 13 10:49:20 mfschunksrv2backup mfschunkserver[25585]: scanning folder /mfs-volume/: 98% (1040s)
Jan 13 10:49:22 mfschunksrv2backup mfschunkserver[25585]: scanning folder /mfs-volume/: 99% (1042s)
Jan 13 10:49:30 mfschunksrv2backup mfschunkserver[25585]: scanning folder /mfs-volume/: complete (1050s)
Jan 13 10:53:42 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:42 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:42 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:42 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:42 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:42 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:47 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:49 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:52 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
Jan 13 10:53:55 mfschunksrv2backup mfschunkserver[25585]: replicator: connect timed out
```


I suppose this is due to missing chunks. We are ready to refuse data that could not be copied from old chunkservers. Just to keep the rest of the data and start MooseFS fully. 

Any ideas? Thanks!

**Comment by IYEO** [comment]
We noticed one trait on some old chunkservers (QNAP NAS)...
Size of some directories in mounted partition designed for the chunks of the system (i.e. "BF/", "18/") is much larger (~700 Gb) than other directories` size (~ 10 Gb).

**Comment by chogata** [comment]
We checked and there were no changes in the networking part of MooseFS's code from 3.103 to 3.109.

This looks very much like a network problem - your chunk servers can connect to the master, but they cannot connect to each other. Or, more specifically, .122 can't connect to .123. Is chunk server on .123 working okay, no high load in system? Can you ping/telnet/ssh from machine .122 to machine .123?

Also, a side note: if you copied all data from old chunk servers to new ones via rsync and some chunks did not copy, you should delete the _.chunkdb_ files from the hard drives your chunk servers use for chunk storage (only if you copied them also when you did the rsync). If you don't do it, then the chunk servers won't "know" that some of the chunks did not copy and you will get read error later on and could potentially loose more data.
Don't delete all _.chunkdb_ files at the same time, one per sever only and not all servers at the same time. As you have only 3 chunk servers, I would recommend doing it one at a time. You should, for each chunkserver:
- stop it
- delete one _.chunkdb_ file
- start it
- let it finish the startup scanning process (might take some time, as it will need to re-create the _.chunkdb_ file you've just deleted)
- repeat the process untill all _.chunkdb_ on this chunkserver are re-created

**Comment by IYEO** [comment]
Thanks for the reply, @chogata!

We resolved the problem with `replication status: Can't connect` and MooseFS is working with new chunkservers perfectly now.
Port 9422 on new chunkservers had been blocked by firewall (initially "new chunkservers" intended for other purposes, therefore we did not pay attention to it immediately).

The initial problem `connection with mfs_chunkserver_ip:port timed out` I associate with poor performance of old chunkservers (LXC on QNAP NAS).

I think the issue may be closed. But the question remains about the different size of directories. Is it normal behavior for MooseFS?

**Comment by chogata** [comment]
Yes, this is a normal behaviour. This is because of how local file system cache behaves. On most OSes, cache works better if it does not have to remember too many directories at the same time. Therefore MooseFS does not try to spread the chunks evenly between directories, but rather uses one until it reaches its internal quota of chunks, then moves to the next, to the next and so on. General observations shows that the most frequently used files are usually the ones least recently recorded, so this solution works best in most situations.

**Comment by IYEO** [comment]
Thanks again for reply, @chogata!

**Comment by onlyjob** [comment]
> MooseFS does not try to spread the chunks evenly between directories, but rather uses one until it reaches its internal quota of chunks, then moves to the next, to the next and so on. General observations shows that the most frequently used files are usually the ones least recently recorded, so this solution works best in most situations.

OMG I always thought it is a bug but it turned out to be intentionally bad design based on assumptions. :( This "solution" only makes overall performance worse.

Even or random distribution of chunk files among chunkserver directories is always better than dis-proportionally greater number of chunks in some directories. Mainly because distribution reduces access concentration. More data in one place means more hits, more congestion and less benefits from distribution. Imagine one chunkserver having 40...50 times more data than any other chunkserver -- guess which chunkserver would be the busiest?? Same thing with number of files per directory. Here is pragmatic example from one chunkserver HDD (first column - seconds to walk; second column - directory; third column - number of files):

~~~~
$  for D in $(find -maxdepth 1 -type d -printf '%P\n' | sort); do \
printf ":: $D :: "; tree $D | wc -l; done | ts -i %s

8 :: 00 :: 45112
3 :: 01 :: 39850
2 :: 02 :: 45017
2 :: 03 :: 44686
3 :: 04 :: 43994
2 :: 05 :: 41658
2 :: 06 :: 40154
4 :: 07 :: 40048
29 :: 08 :: 244076
3 :: 09 :: 42750
2 :: 0A :: 45197
2 :: 0B :: 45364
2 :: 0C :: 42651
3 :: 0D :: 42456
2 :: 0E :: 45458
2 :: 0F :: 42104
2 :: 10 :: 42145
2 :: 11 :: 43952
1 :: 12 :: 42432
2 :: 13 :: 45485
3 :: 14 :: 45673
2 :: 15 :: 44992
2 :: 16 :: 45443
2 :: 17 :: 40049
2 :: 18 :: 45005
2 :: 19 :: 45306
2 :: 1A :: 42005
3 :: 1B :: 45535
2 :: 1C :: 45485
2 :: 1D :: 44972
2 :: 1E :: 45384
2 :: 1F :: 45656
2 :: 20 :: 45605
2 :: 21 :: 42786
2 :: 22 :: 45094
2 :: 23 :: 43966
2 :: 24 :: 45457
2 :: 25 :: 42309
2 :: 26 :: 45562
2 :: 27 :: 40002
2 :: 28 :: 45588
1 :: 29 :: 40124
2 :: 2A :: 45760
2 :: 2B :: 45556
2 :: 2C :: 40880
1 :: 2D :: 45507
2 :: 2E :: 44101
2 :: 2F :: 40143
2 :: 30 :: 45456
1 :: 31 :: 45587
2 :: 32 :: 45521
2 :: 33 :: 44904
2 :: 34 :: 44025
2 :: 35 :: 40066
2 :: 36 :: 45567
2 :: 37 :: 43891
3 :: 38 :: 38642
2 :: 39 :: 40785
1 :: 3A :: 40365
2 :: 3B :: 50906
3 :: 3C :: 46865
1 :: 3D :: 45387
2 :: 3E :: 45597
2 :: 3F :: 45433
2 :: 40 :: 42164
2 :: 41 :: 45673
2 :: 42 :: 38552
2 :: 43 :: 45663
2 :: 44 :: 45406
1 :: 45 :: 45360
2 :: 46 :: 45485
2 :: 47 :: 45442
2 :: 48 :: 45612
2 :: 49 :: 45417
2 :: 4A :: 44002
2 :: 4B :: 45709
2 :: 4C :: 45551
2 :: 4D :: 44162
2 :: 4E :: 42338
2 :: 4F :: 43851
2 :: 50 :: 45363
3 :: 51 :: 42380
3 :: 52 :: 45255
2 :: 53 :: 45648
2 :: 54 :: 45430
3 :: 55 :: 43788
2 :: 56 :: 45631
2 :: 57 :: 38531
2 :: 58 :: 40189
2 :: 59 :: 42682
2 :: 5A :: 38416
2 :: 5B :: 38464
1 :: 5C :: 42466
2 :: 5D :: 42048
2 :: 5E :: 45315
2 :: 5F :: 41650
2 :: 60 :: 38572
1 :: 61 :: 42315
2 :: 62 :: 38717
2 :: 63 :: 38561
2 :: 64 :: 42442
2 :: 65 :: 43784
1 :: 66 :: 42390
2 :: 67 :: 38843
2 :: 68 :: 42262
2 :: 69 :: 42175
2 :: 6A :: 42375
2 :: 6B :: 39840
2 :: 6C :: 38845
1 :: 6D :: 38553
3 :: 6E :: 42256
2 :: 6F :: 42517
2 :: 70 :: 38588
2 :: 71 :: 38615
1 :: 72 :: 42343
3 :: 73 :: 42434
1 :: 74 :: 42556
2 :: 75 :: 39992
2 :: 76 :: 38606
2 :: 77 :: 45634
2 :: 78 :: 45402
1 :: 79 :: 38542
2 :: 7A :: 43878
2 :: 7B :: 38481
2 :: 7C :: 42255
1 :: 7D :: 53235
3 :: 7E :: 42451
2 :: 7F :: 42529
1 :: 80 :: 40449
2 :: 81 :: 38468
2 :: 82 :: 42201
2 :: 83 :: 43858
1 :: 84 :: 45791
161 :: 85 :: 1961750
2 :: 86 :: 43868
2 :: 87 :: 42475
2 :: 88 :: 43470
2 :: 89 :: 40532
1 :: 8A :: 42686
2 :: 8B :: 42257
2 :: 8C :: 42918
53 :: 8D :: 234492
1 :: 8E :: 44002
2 :: 8F :: 42235
2 :: 90 :: 40394
2 :: 91 :: 44864
2 :: 92 :: 45255
2 :: 93 :: 41999
2 :: 94 :: 41799
1 :: 95 :: 38596
3 :: 96 :: 42744
1 :: 97 :: 42465
2 :: 98 :: 38387
2 :: 99 :: 38565
2 :: 9A :: 42571
2 :: 9B :: 42355
153 :: 9C :: 1322210
3 :: 9D :: 42405
2 :: 9E :: 40034
3 :: 9F :: 44811
2 :: A0 :: 38631
2 :: A1 :: 45187
2 :: A2 :: 42325
2 :: A3 :: 38592
2 :: A4 :: 38516
2 :: A5 :: 40494
115 :: A6 :: 1192862
2 :: A7 :: 38511
2 :: A8 :: 45001
2 :: A9 :: 42399
2 :: AA :: 39865
1 :: AB :: 38652
3 :: AC :: 43823
2 :: AD :: 45640
2 :: AE :: 40367
2 :: AF :: 43941
2 :: B0 :: 45488
2 :: B1 :: 46192
2 :: B2 :: 42293
63 :: B3 :: 804730
3 :: B4 :: 42213
2 :: B5 :: 45559
2 :: B6 :: 40320
2 :: B7 :: 45614
2 :: B8 :: 42670
2 :: B9 :: 38750
2 :: BA :: 42219
369 :: BB :: 3622774
3 :: BC :: 43950
3 :: BD :: 38513
3 :: BE :: 42749
3 :: BF :: 42186
2 :: C0 :: 44939
2 :: C1 :: 44043
2 :: C2 :: 42281
2 :: C3 :: 38511
3 :: C4 :: 40576
2 :: C5 :: 42385
2 :: C6 :: 42104
2 :: C7 :: 38608
2 :: C8 :: 42751
2 :: C9 :: 40154
2 :: CA :: 38682
1 :: CB :: 43832
2 :: CC :: 45574
2 :: CD :: 42634
2 :: CE :: 42255
2 :: CF :: 45347
2 :: D0 :: 42330
2 :: D1 :: 42361
2 :: D2 :: 45601
3 :: D3 :: 44261
1 :: D4 :: 45207
2 :: D5 :: 45777
3 :: D6 :: 38637
2 :: D7 :: 44850
1 :: D8 :: 38559
3 :: D9 :: 42346
2 :: DA :: 38667
2 :: DB :: 44973
124 :: DC :: 1062189
2 :: DD :: 44040
2 :: DE :: 42282
2 :: DF :: 44054
2 :: E0 :: 45583
3 :: E1 :: 45304
2 :: E2 :: 44050
2 :: E3 :: 44019
2 :: E4 :: 42356
2 :: E5 :: 38628
2 :: E6 :: 38696
2 :: E7 :: 45415
3 :: E8 :: 41575
2 :: E9 :: 44003
2 :: EA :: 45469
3 :: EB :: 40114
2 :: EC :: 45564
2 :: ED :: 41276
2 :: EE :: 45604
2 :: EF :: 40099
2 :: F0 :: 45714
2 :: F1 :: 44809
2 :: F2 :: 45635
2 :: F3 :: 45215
2 :: F4 :: 38525
2 :: F5 :: 40062
2 :: F6 :: 45575
2 :: F7 :: 44073
216 :: F8 :: 339613
1 :: F9 :: 42408
3 :: FA :: 45703
2 :: FB :: 42413
2 :: FC :: 43974
2 :: FD :: 44224
2 :: FE :: 45548
1 :: FF :: 46093
~~~~

Note abnormally large directory `BB` - 80 times heavier than most with walk time 123 times slower.
As you can see several directories have 40...50 times more files than most directories and walk time on those large directories is slow. Probabilistically heavy directories get more hits and overall performance suffers.

As far as I'm concerned disproportional distribution of chunk files among directories is a bug, or more precise, anti-feature. Please consider making it configurable or preferably remove the flawed distribution logic entirely. Thanks.

**Comment by chogata** [comment]
I may have not explained myself 100% clearly. The "internal quota of chunks" is not a maximum number of chunks one directory can have inside. It's a set number of chunks (10000), after which we move to the next directory, and next, and next, round-robin like. We will eventually re-visit each directory and add more chunks if there are enough being stored on one chunk server. We spent several weeks on testing that and our tests showed this is much more efficient than completely even distribution of chunks between directories, because of how most OSes cache behaves.

Now, maximum single chunk size is 64MiB. Times 10000 gives us roughly 640GB of data. Plus, with deletions, the 10000 is not a hard limit of chunk count difference, it might get slightly more in some cases (but not much more - the algorithm accounts for deletions and adjusts the round-robin general behaviour accordingly). So when somebody mentions ~700GiB vs 10GiB of chunk data, it's not totally improbable, although it's borderline behaviour.

Nevertheless, the algorithm means you never should have ended with **chunk count** (not size!) difference much bigger than 10000 between two directories. For sure never bigger than 20000 in any case. Your example shows us that there is a bug in the algorithm somewhere. We will investigate that. But it's the implementation, that is flawed, not the design.

**Comment by onlyjob** [comment]
@chogata, after what I've written how could you not understand and still insist it is not a flawed design? It is beyond me. Your _tests_ make some assumptions and that's why in artificial testing distribution algorithm may perform faster. In reality it can not be predicted which chunks are more frequently. Distribution algorithm probably optimises for test workflow.
Optimising for a certain particular workflow that behaves as you describe is likely to penalise all different workflows.

IMHO both implementation and design are flawed.

I'm branching-off this issue as #326.
