### ISSUE TITLE
CGI: master charts fail: "ValueError: invalid literal for int()"

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#325]
~~~~
Traceback (most recent call last):
  File "/usr/share/moosefs-cgi/mfs.cgi", line 6893, in 
    manc = int(mchtmp[2])
ValueError: invalid literal for int() with base 10: '1§ions=IN'
~~~~

**Comment by acid-maker** [comment]
You have garbage in your URL - parameter MCdata should have string (host/ip) , colon , port , colon , number of chart. Something like this:
```http://127.0.0.1:9425/mfs.cgi?sections=MC&MCdata=172.17.2.61:9421:1```
In your case you have some garbage (`§ions=IN`) after MCdata parameter - this is why cgi can't convert it to number. I don't believe that such URL has been generated by CGI. If yes - then let me know how to repeat that.
I can add try/except to catch such wrong URLs, but it is not so important since it should never happen in normal system use. Of course if this garbage has been somehow generated by cgi/cgiserv itself then we should find the source of this problem.

**Comment by onlyjob** [comment]
Thanks, clearing URL helped but I did not add anything there! Garbage got there somehow by clicking through CGI tabs but I do not know how to reproduce... Let's close due to lack or reproducer...
