### ISSUE TITLE
[feature] create and remove snapshots without mounting the filesystem

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#355]
Hi,

Some of the administrative commands require only connection to the master, like mfsdirinfo or mfscli

Would it be possible to run mfsmakesnapshot and mfsrmsnapshot without mounting the filesystem, just with access to the master?

**Comment by chogata** [comment]
Hi,

Mfsdirinfo does not work without a mounted filesystem. Maybe you were thinking about mfsmetadirinfo? This does not require a mounted filesystem, but it also does not connect to mfsmaster, it works on a local copy of metadata file and is a read only kind of tool.

The only tool that connects directly to the master is mfscli, all other require mounted filesystem and this is by design, for security reasons.

**Comment by eleaner** [comment]
Thank you
