### ISSUE TITLE
Internal rebalancing stops after emptying HDD marked as `<`.

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#364]
As subject says, after emptying HDD marked with `<` internal rebalancing stopped despite some local HDDs being filled up to 100% (as result of `<` rebalancing) while some local HDDs utilised well below average (within 35%...60% range).
This is in high-speed rebalancing mode.

**Comment by chogata** [comment]
This is by design - when there are disks with `<` present, internal rebalance takes them always as source disks for copying. We assumed that a disk marked with `<` will be removed from the chunkserver as soon as it is empty. But we could probably change that behaviour a bit and start ignoring `<` disks after they are completely empty. I will add it to our feature list.

**Comment by onlyjob** [comment]
This problem has been fixed. Thank you.
