### ISSUE TITLE
[question] copy-on-write

### ISSUE THREAD

**Issue by eleaner** [moosefs/moosefs#386]
Hi,

Could you please explain, 
if I copy a file from one location in mfs mount to another location in the same mount.
Is this operation duplicating chunks or only pointing the new location to the existing chunks?

Thanks

**Comment by chogata** [comment]
Hi,

Copying duplicates chunks, always. `cp` operation in shell is sent by the kernel to mfs as a read and a write - mfs doesn't even know a user wanted to make a copy.
If you want to have copy-on-write, you can use the snapshot mechanism we made partly also because of the above. See the man for `mfsmakesnapshot`. This is basically the copy-on-write mechanism you are asking about.

**Comment by tianon** [comment]
The `cp` command does have a `--reflink` flag that's supposed to be able to create a lightweight copy:

```
When --reflink[=always] is specified, perform a lightweight copy, where the
data blocks are copied only when modified.  If this is not possible the copy
fails, or if --reflink=auto is specified, fall back to a standard copy.
Use --reflink=never to ensure a standard copy is performed.
```

Any idea how that's implemented?  Hopefully it's not specific filesystem whitelisting / implementation, and something more standardized that `mfsmount` could possibly take advantage of?

**Comment by rafamiga** [comment]
Take a look at this video, it's explained there:

https://www.youtube.com/watch?v=WqJoytkNrt8&t=3048

**Comment by chogata** [comment]
FUSE does not support the mechanizm that Linux file systems use to achieve `cp --reflink`. But `mfsmakesnapshot` behaves almost exactly like `cp --reflink` plus, it has bonus features: works on everything MooseFS works on, is atomic (because it's performed entirely in the master's memory) and the users get tools that enable them to also quickly remove whole snapshots.
