### ISSUE TITLE
free documentation

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#4]
I'd love to see PDF documentation sources committed to this repository under GPL-2+ license.

**Comment by oxide94** [comment]
As I am responsible for developing documentation, I assigned this issue to myself. It makes a sense for me and probably could help improve documentation. I'm considering releasing it as a new, parallel project (next to MooseFS sources and MooseFS ports for FreeBSD).

**Comment by onlyjob** [comment]
Great. :) Just curious, why not in this repository? It is not too big so perhaps not because of its size?

**Comment by onlyjob** [comment]
Also setting-up Wiki might be useful.

**Comment by oxide94** [comment]
> Great. :) Just curious, why not in this repository? It is not too big so perhaps not because of its size?

Noooo :) Size of all `*.tex` source files summed up is 212 kB, so it is not big. We'll discuss it among our team and decide in which way it should be released.

Generally speaking I already do have a Git repos for documentation (with all commits) on our server (but still - a different repo for each document...), so it would be simpler to just move it to a new project (with all previous commits). But in this case every document would be a different project. And `.git` folders actually are big (summed up: ~78 MB), because they contain binary PDFs and their history... I must figure out the best solution. Probably adding `*.pdf` to `.gitignore` would be a good step. Maybe you have any idea?

> Also setting-up Wiki might be useful.

Yes, I haven't started creating Wiki on GitHub (even containing basic usage info etc.) yet. I have it in my mind.

**Comment by onlyjob** [comment]
There are some techniques to edit git history in order to remove pre-built files like PDF but I don't have much experience with those. If you want to preserve history then I'd suggest to create a new project. Otherwise it would be great to have software and its documentation in one place (repository) under same license.
Also you can archive old repository and just commit .tex files here...

**Comment by dkorzhevin** [comment]
Hello guys,

Any update regarding this documentation question, please?

Dmitry

**Comment by oxide94** [comment]
@dkorzhevin 
Hi Dmitry,

yes, of course :)
We're going to release sources of documentation on GPL-2+ / MIT license (we haven't decided yet), but before this we want to fix known issues in MooseFS documentation (e.g. I'm in the middle of Labels / Storage Classes Manual improvements at the moment).

Peter

**Comment by onlyjob** [comment]
Please consider the following: https://people.debian.org/~bap/dfsg-faq.html#docs

Also it would be great to fix #5 first.

**Comment by Rondom** [comment]
You may want to have a look at https://git-scm.com/docs/git-filter-branch to rewrite the git history to exclude the binary pdf-files. Of course adding a [.gitignore such as this one](https://www.gitignore.io/api/latex) can avoid accidentally adding PDFs and other generated files.

**Comment by oxide94** [comment]
Hey guys, thanks for your comments! I'd like to come back to this issue and proceed soon.

The major aspect of resolving this issue is place again (it was mentioned above, but let's re-consider it) - what do you think would be better? Regarding commits history now I don't think it is very crucial, so let's assume there will be whole `*.tex` files committed as an initial docs release. It will be much simpler.

Is it better to put it into a new repo ([like MooseFS FreeBSD Ports repo](https://github.com/moosefs/FreeBSD-ports)) or into this repo?

Regarding the license I will follow @onlyjob advice (thanks!) and docs will be released under the same license MooseFS code is released.

**Comment by oxide94** [comment]
@onlyjob @dkorzhevin @Rondom [Documentation released](https://github.com/moosefs/Documentation) :)

**Comment by onlyjob** [comment]
Thanks. Free documentation is a big step forward but choice of license is disappointing. It really should be _GPL-2 or later versions_. Licensing as _GPL-2 only_ is a seriously bad practice. :(
Why MooseFS makes such [terrible licensing decisions](https://github.com/moosefs/moosefs/issues/5)?

**Comment by oxide94** [comment]
Hi @onlyjob,

I've followed your advice in [this comment](https://github.com/moosefs/moosefs/issues/4#issuecomment-224249874) and released the documentation sources under the same license as MooseFS licensed is at the moment. Of course you mentioned, that "it would be great to fix #5 first", but we didn't want to block documentation releasing because of lack of decision on it.

If MooseFS license will change, documentation license also will, I think the homogeneity here is a good thing (as you mentioned in your comment) :), but whole licensing aspect of the project is not up to me...

Best
Peter

**Comment by onlyjob** [comment]
There is no contradiction with my previous suggestion. :) Licensing documentation under the same terms as code is a good practice. However not limiting license to GPL-2 _only_ would be even better while perfectly compatible with main MooseFS license.
