### ISSUE TITLE
I/O errors reported by chunkserver after growing filesystem and reload

### ISSUE THREAD

**Issue by marcin-github** [moosefs/moosefs#41]
moosefs-3.0.88
I resized filesystem from 20GB to 50GB. As expected chunkserver throws:
`Feb 10 13:41:29 ch1 mfschunkserver[10411]: disk: /var/lib/mfs/chunks/ ; number of total blocks has been changed significantly (5238272 -> 13104640) - mark it as damaged`
Next I sent HUP to mfs-chunkserver - I hope this change state from damaged to online. But I got:

`Feb 10 13:42:03 ch1 mfschunkserver[10411]: reloading config files`
`Feb 10 13:42:03 ch1 mfschunkserver[10411]: main server module: socket address hasn't changed (*:9422)`
`Feb 10 13:42:03 ch1 mfschunkserver[10411]: reloading hdd data ...`
`Feb 10 13:42:03 ch1 mfschunkserver[10411]: hdd space manager: folder /var/lib/mfs/chunks/ will be scanned`
`Feb 10 13:42:04 ch1 mfschunkserver[10411]: scanning folder /var/lib/mfs/chunks/: complete (0s)`
`Feb 10 13:42:05 ch1 mfschunkserver[10411]: connecting ...`
`Feb 10 13:42:05 ch1 mfschunkserver[10411]: connected to Master`
`Feb 10 13:42:08 ch1 mfschunkserver[10411]: hdd_io_begin: file:/var/lib/mfs/chunks//00/chunk_00000000000001CC_00000002.mfs - open error: ENOENT (No such file or directory)`
`Feb 10 13:42:09 ch1 mfschunkserver[10411]: set_chunk_version: file:/var/lib/mfs/chunks//00/chunk_00000000000001B8_00000008.mfs->/var/lib/mfs/chunks//00/chunk_00000000000001B8_00000009.mfs - rename error: ENOENT (No such file or directory)`
`Feb 10 13:42:18 ch1 mfschunkserver[10411]: hdd_io_begin: file:/var/lib/mfs/chunks//00/chunk_00000000000001BC_0000000A.mfs - open error: ENOENT (No such file or directory)`
`Feb 10 13:42:19 ch1 mfschunkserver[10411]: 3 errors occurred in 600 seconds on folder: /var/lib/mfs/chunks/`

After this I restarted chunkserver and it started work correctly. Is it my fault - should I stop chunkserver before resize filesystem?

**Comment by xandrus** [comment]
Hi,
Please try to change your setting in mfshdd.cfg file.
We have special option for such a situation:

Please add ~ at the begging of your chunks folder

~/var/lib/mfs/chunks/ 

This is description:
#  - '~' means that significant change of total blocks count will not mark this drive as damaged

**Comment by marcin-github** [comment]
But why error " hdd_io_begin ..." appeared?

**Comment by oxide94** [comment]
Cześć @marcin-github,

`hdd_io_begin` could have appeared because when you were resizing the filesystem, the currently resized block might be used by `mfschunkserver`.

Such fragile modifications shouldn't be done when processes are performing I/O operations on a filesystem (of course including `mfschunkserver`, but I mean in general). The proper way to do grow the filesystem is as follows:

1. Enable maintenance mode for the specific Chunkserver via MFS CGI (tab `Servers`) or via MFSCLI: `mfscli -CM1/ip_of_chunkserver/port_of_chunkserver`
2. Stop `mfschunkserver` process: `mfschunkserver stop` or your system's specific command (`service...` / `systemctl...`)
3. Grow the filesystem
4. Start `mfschunkserver process`
5. Disable maintenance mode for the specific Chunkserver via MFS CGI (tab `Servers`) or via MFSCLI: `mfscli -CM0/ip_of_chunkserver/port_of_chunkserver`

Of course in case of any further questions, please don't hesitate to ask! :)

Best regards / Pozdrawiam
Peter / MooseFS Team

**Comment by jamarat** [comment]
How about unnecessary / at the end of /var/lib/mfs/chunks/ what makes double // :
/var/lib/mfs/chunks//00/chunk_00000000000001B8_00000009.mfs

**Comment by oxide94** [comment]
@jamarat: yes, double `/` can be removed, but it actually shouldn't affect I/O operations.

Resizing the filesystem in a mentioned by @marcin-github way may be dangerous for data stored on a filesystem. Fortunately MooseFS is fault-tolerant, so if you have goal >= 2, MooseFS will automatically replicate eventual missing chunk(s) from a second copy.

**Comment by marcin-github** [comment]
Cześć @oxide94 ,
I don't know what did you meant in "the currently resized block might be used by mfschunkserver". I resized filesystem many times while fs was under heavy load (postgres, mysql, or other services, on ext4 or xfs) and never ever I didn't had any issue with it. Only "issue" was frozed I/O for a while.

@jamarat double slash is because in mfshdd.cfg I have:
/var/lib/mfs/   - slash on the end.

**Comment by xandrus** [comment]
I would like to add that we added such a security - `number of total blocks has been changed significantly` in MooseFS chunkserver in case of hdd error.
We had such a situation when hard disk crashed and started to report in 1PB HDD in system.

When you want to resize hard disk you have to add `~` at the beginning of hdd path.

**Comment by oxide94** [comment]
> I don't know what did you meant in "the currently resized block might be used by mfschunkserver".

Ok, sorry, I read everything once again. It is not true of course. I will edit my previous reply not to mislead other users. Sorry.

Theoretically such resize (growing) of the filesystem should work properly on working, mounted FS. I just had a bad experience with it once in the past and now, when I have to do it, I always try to do it in the most safest way I can. Nevermind.

As @xandrus wrote:
> When you want to resize hard disk you have to add ~ at the beginning of hdd path.

If you do so, `mfschunkserver` will not consider such HDD as damaged. (Of course after doing so, please don't forget to reload the Chunkserver process).

**Comment by marcin-github** [comment]
Thanks for answers. I think that we are not focusing on the same problem but nevermind. I didn't have any data loss nor other problems so if you don't see anything wrong with it then it's also ok for me:)

**Comment by oxide94** [comment]
@marcin-github 

Messages you mentioned:

```
Feb 10 13:42:08 ch1 mfschunkserver[10411]: hdd_io_begin: file:/var/lib/mfs/chunks//00/chunk_00000000000001CC_00000002.mfs - open error: ENOENT (No such file or directory)
Feb 10 13:42:09 ch1 mfschunkserver[10411]: set_chunk_version: file:/var/lib/mfs/chunks//00/chunk_00000000000001B8_00000008.mfs->/var/lib/mfs/chunks//00/chunk_00000000000001B8_00000009.mfs - rename error: ENOENT (No such file or directory)
Feb 10 13:42:18 ch1 mfschunkserver[10411]: hdd_io_begin: file:/var/lib/mfs/chunks//00/chunk_00000000000001BC_0000000A.mfs - open error: ENOENT (No such file or directory)
```

actually mean, that Chunkserver wanted to open chunk `1CC` (1st), increase chunk's `1B8` version (2nd) an open chunk `1BC` (3rd) - and in each case failed, because for some reason these files were not present.

We'll check it out with our developers next week and get back to you. What filesystem exactly do you have? XFS or EXT4?

Peter

**Comment by marcin-github** [comment]
xfs, kernel 3.18. Thank you
