### ISSUE TITLE
moosefs  changelog  not  rotate,that make changelog.0.mfs become huge big . 

### ISSUE THREAD

**Issue by Damien9527** [moosefs/moosefs#44]
so is any idea of why the changlog did not rotate. the master cfg file is not make any change.

like this .
[root@yz381 mfs]# ll -h
total 7.0G
-rw-r----- 1 mfs mfs 177M Mar  9 15:20 bak.changelog.0.mfs
-rw-r----- 1 mfs mfs 673M Mar  8 05:27 bak.metadata.mfs.back
-rw-r----- 1 mfs mfs 4.0G Mar  9 20:18 changelog.0.mfs
-rw-r--r-- 1 mfs mfs 845M Mar  9 15:27 metadata.mfs.back
-rw-r----- 1 mfs mfs 854M Mar  8 05:24 metadata.mfs.back.tmp
-rw-r----- 1 mfs mfs 530M Mar  9 15:21 metadata.mfs.emergency
-rw-r----- 1 mfs mfs  22K Mar  9 19:59 sessions.mfs
-rw-r----- 1 mfs mfs 745K Mar  9 20:00 stats.mfs

**Comment by zcalusic** [comment]
Check the ownership/permissions of the /var/lib/mfs folder. Should be mfs:mfs, at least mode 700.

And check master syslog to see what it reports. It should rotate changelogs every hour, and report something if it fails.

**Comment by oxide94** [comment]
Hi @xiewei9527,

Could you please share with us what version of MooseFS do you use?
Are there any operations made on MooseFS?

Best regards,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
@zcalusic @oxide94 
the version is 1.6.25 .

/var/log/message:  show like this 

Mar  9 20:39:17 yz381 mfsmaster[9276]: chunk 0000000013A1AB7B_00000008 - invalid copy on (10.39.3.104 - ver:00000009)
Mar  9 20:39:52 yz381 mfsmaster[9276]: chunk 000000001B73BF4E has only invalid copies (2) - please repair it manually
Mar  9 20:39:52 yz381 mfsmaster[9276]: chunk 000000001B73BF4E_00000005 - invalid copy on (10.39.3.102 - ver:00000006)
Mar  9 20:39:52 yz381 mfsmaster[9276]: chunk 000000001B73BF4E_00000005 - invalid copy on (10.39.3.97 - ver:00000006)
Mar  9 20:40:28 yz381 mfsmaster[9276]: chunk 000000001B74144A has only invalid copies (2) - please repair it manually
Mar  9 20:40:28 yz381 mfsmaster[9276]: chunk 000000001B74144A_00000004 - invalid copy on (10.39.3.98 - ver:00000005)
Mar  9 20:40:28 yz381 mfsmaster[9276]: chunk 000000001B74144A_00000004 - invalid copy on (10.39.3.88 - ver:00000005)
Mar  9 20:40:58 yz381 mfsmaster[9276]: chunk 000000000EE76163 has only invalid copies (2) - please repair it manually
Mar  9 20:40:58 yz381 mfsmaster[9276]: chunk 000000000EE76163_00000010 - invalid copy on (10.39.3.100 - ver:00000011)
Mar  9 20:40:58 yz381 mfsmaster[9276]: chunk 000000000EE76163_00000010 - invalid copy on (10.39.3.105 - ver:00000011)
Mar  9 20:41:19 yz381 mfsmaster[9276]: chunk 000000001B739371 has only invalid copies (2) - please repair it manually
Mar  9 20:41:19 yz381 mfsmaster[9276]: chunk 000000001B739371_00000001 - invalid copy on (10.39.3.97 - ver:00000002)
Mar  9 20:41:19 yz381 mfsmaster[9276]: chunk 000000001B739371_00000001 - invalid copy on (10.39.3.102 - ver:00000002)


the first time i restart the master ,is not succes ,i use the mfsmetarestore -a   ,the  master go up .

but  after that , the changlog didnot rotate

i restart mfsmater faild,because the space is not enough ,   then i mv the away the changlog.0.mfs  ,then use the mfsmetarestore -a  ,the i restart the master success  .

**Comment by xiewei9527** [comment]
hello,  the log here .

Mar  9 20:00:00 yz381 mfsmaster[9276]: previous metadata save process hasn't finished yet - do not start another one

**Comment by xandrus** [comment]
Hi.

This MooseFS version is not supported:
https://moosefs.com/support.html

Please try to update MooseFS to 2.0.91 version.

**Comment by xiewei9527** [comment]
is there any idea why this happend .    so worry about on line .  Thanks very much for you reply .

**Comment by xandrus** [comment]
Hi.

Please read this document according free space calculation for MooseFS metadata save:
https://moosefs.com/documentation/best-practices.html#space

**Comment by oxide94** [comment]
Hi @xiewei9527,

The end of space for metadata dumps is not a good situation. Please grow the partition on move metadata to the disk / partition with enough free space.

Regarding the problem with rotating changelogs - such situation definitely will not happen with MooseFS 2.0. You mentioned you use MFS 1.6 - this is **very** old version, which has many known bugs. Last MFS 1.6.27 release was almost 5 years (!) ago. These known bugs have already been fixed in MooseFS 2.0 and 3.0.

We strongly recommend upgrading to MooseFS 2.0 or 3.0 - this process is quite easy and straight-forward. Please read "MooseFS 2.0 Upgrade Guide". You can obtain it from: https://moosefs.com/documentation/moosefs-2-0.html

In case of any questions, we are happy to help.

Best regards,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
@oxide94   i find that  the  permissions  of   metadata.mfs.back  before is  root :root ,  
  then i change the to mfs,    but i don't restart the master .  should i reload  or restart  it ?     maybe is the problem ?

**Comment by oxide94** [comment]
Hi @xiewei9527,

the most important question at the moment is: how many free space at the moment do you have in `/var/mfs` or `/var/lib/mfs`? Please don't stop the Master Server if your free space is close to 0.

Could you please paste the output of `df -h`?

Best,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
@oxide94    the space used is 100GB, and  used 90%.   the changelog is 60G,    then i restart  the master  failed.

**Comment by oxide94** [comment]
Hi @xiewei9527 ,

I understand you can't start the Master Server.

Please:
0. stop Master Server (if it is not stopped)
1. change permissions to `/var/mfs` or `/var/lib/mfs` to `mfs:mfs` recursively: `chown -R mfs:mfs /var/lib/mfs /var/mfs`
2. run `mfsmetarestore -a` - it should combine changelog(s) and `metadata.mfs.back` file to new `metadata.mfs`.
3. if `mfsmetarestore -a` restore metadata successfully, move (**not delete**) `changelog.0.mfs` somewhere, as it is not needed if there is a proper `metadata.mfs` (**not** `.back`!) file. You can gzip it for example to free a lot of needed space
4. start Master Server and check if situation is stable.
5. Let me know :)

If it go successfully, I **strongly** recommend to upgrade to MFS 2.0. Your issue may be caused by bug in MFS 1.6, which is not going to be fixed, because MFS 1.6 is not being developed anymore.


Best regards,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
hello  @oxide94,  

my cluster is working online , we are copy file  out from it ,after that ,we will take your advise to have a try. 

here i find  metadata.mfs.back.tmp   in the data  path.  someone says  this file is create when the master is stopped  unnormaly.    should it be the reason.    If i move away metadata.mfs.back.tmp  , will this cause the working master  become failed  ?

**Comment by oxide94** [comment]
Hi @xiewei9527,

No, it shouldn't influence working Master Server at all.

Best regards,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
Hi ,@oxide94  @xandrus @onlyjob   .Thanks  for all of your  kindly  reply . 

       Thank godness.  when i mv the  metadata.mfs.back.tmp   away , the changelog  rotate   successful .   

        should this tmp  file be a bug in the old version ?  why this file created but not  processed  after the   mfsmaster restart  or  metadatarestore   ?   Did  the 3.x version still have this problem ? 
      
        the next step ,  we consider update our cluster to  MFS 3.0.88 .

**Comment by oxide94** [comment]
Hi @xiewei9527,

Actually I have no idea about this `.tmp` file. In MFS 3.0.88 or MFS 2.0.91 there is definitely no such behaviour. But please remember, that enough amount of free space in `/var/lib/mfs` (or `/var/mfs` in 1.6) is one of the most crucial things.

Best regards,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
Hi, @oxide94 :
     Thanks  for your  remind .  
    Here is another question.    how to repair the chunk  ?   mfsfilerepair ?　

Mar 10 09:18:10 yz381 mfsmaster[9276]: chunk 000000001A593A6C_00000005 - invalid copy on (10.39.3.89 - ver:00000006)
Mar 10 09:18:26 yz381 mfsmaster[9276]: chunk 000000000FE00D62 has only invalid copies (2) - please repair it manually
Mar 10 09:18:26 yz381 mfsmaster[9276]: chunk 000000000FE00D62_0000000C - invalid copy on (10.39.3.106 - ver:0000000D)
Mar 10 09:18:26 yz381 mfsmaster[9276]: chunk 000000000FE00D62_0000000C - invalid copy on (10.39.3.92 - ver:0000000D)
Mar 10 09:18:28 yz381 mfsmaster[9276]: chunk 000000001A6BDD74 has only invalid copies (2) - please repair it manually
Mar 10 09:18:28 yz381 mfsmaster[9276]: chunk 000000001A6BDD74_00000001 - invalid copy on (10.39.3.94 - ver:00000002)
Mar 10 09:18:28 yz381 mfsmaster[9276]: chunk 000000001A6BDD74_00000001 - invalid copy on (10.39.3.98 - ver:00000002)
Mar 10 09:18:28 yz381 mfsmaster[9276]: chunk 000000000F2FE223 has only invalid copies (2) - please repair it manually
Mar 10 09:18:28 yz381 mfsmaster[9276]: chunk 000000000F2FE223_0000000B - invalid copy on (10.39.3.98 - ver:0000000C)
Mar 10 09:18:28 yz381 mfsmaster[9276]: chunk 000000000F2FE223_0000000B - invalid copy on (10.39.3.93 - ver:0000000C)


  and also ,the missing file  only i can find in the  mfscgi  web page.   is there any other way to get it ?

**Comment by oxide94** [comment]
Hi @xiewei9527,

You have to wait for "Filesystem check info" loop to finish - then in MFS CGI you will be able to see paths of missing files.

You can use `mfsfilerepair` tool, but please remember to use is consciously. You can read more about this tool [here](https://moosefs.com/manpages/mfsdiagtools.html).

Best regards,
Peter / MooseFS Team

**Comment by acid-maker** [comment]
On 9 Mar, 2017, at 13:19, xiewei9527 <notifications@github.com> wrote:

> so is any idea of why the changlog did not rotate. the master cfg file is not make any change.
> 
> like this .
> [root@yz381 mfs]# ll -h
> total 7.0G
> -rw-r----- 1 mfs mfs 177M Mar 9 15:20 bak.changelog.0.mfs
> -rw-r----- 1 mfs mfs 673M Mar 8 05:27 bak.metadata.mfs.back
> -rw-r----- 1 mfs mfs 4.0G Mar 9 20:18 changelog.0.mfs
> -rw-r--r-- 1 mfs mfs 845M Mar 9 15:27 metadata.mfs.back
> -rw-r----- 1 mfs mfs 854M Mar 8 05:24 metadata.mfs.back.tmp
> -rw-r----- 1 mfs mfs 530M Mar 9 15:21 metadata.mfs.emergency
> -rw-r----- 1 mfs mfs 22K Mar 9 19:59 sessions.mfs
> -rw-r----- 1 mfs mfs 745K Mar 9 20:00 stats.mfs
> 
> —
> You are receiving this because you are subscribed to this thread.
> 
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Please remove "metadata.mfs.back.tmp" file. Then wait to next even hour - new metadata file should be written and changelogs should start rotating.

This is old bug (fixed in 2.0 as I remember).

-- 
Regards,
Jakub Kruszona-Zawadzki
- - - - - - - - - - - - - - - -
Segmentation fault (core dumped)
Phone: +48 602 212 039

**Comment by oxide94** [comment]
Hey @xiewei9527,

is there anything more we can do to help you on this issue, or can we close it?

If you would have any questions or would encounter any issues during the upgrade to MooseFS 3.0, please don't hesitate to raise a new ticket on GitHub!

Best regards,
Peter / MooseFS Team

**Comment by xiewei9527** [comment]
Hi, @oxide94  
    I see some big changes in MFS3.x ,    Can i upgrade my MFS from 1.6.25 direct to MFS3.0.88 ?  If ok ,  what step should i take.

   If this ok ? 
1、Master Server
2、Chunkservers (in one-by-one scenario)
3、Mounts

**Comment by oxide94** [comment]
Hi @Damien9527,

the official supported and recommended way is to upgrade:

MFS 1.6.25 -> MFS 1.6.27-5 -> MFS 2.0.91 -> MFS 3.0.88

Probably the way MFS 1.6.25 -> MFS 1.6.27-5 -> MFS 3.0.88 will also work fine, but I don't remember we tested it. The most important aspect while upgrading MFS to versions higher than 1.6.x is to start from **1.6.27-5**, so if you have any of previous version, please upgrade to 1.6.27-5 first, then to 2.0 or 3.0.

The order of upgrade you mentioned (1. Master, 2. Chunkservers one-by-one, 3. Mounts) is perfect.

Best regards,
Peter / MooseFS Team

**Comment by Damien9527** [comment]
Hi @oxide94 
    Thanks ,I will try it later.
