### ISSUE TITLE
Why NFS server on MooseFS client is faster than MooseFS client?

### ISSUE THREAD

**Issue by sunnylua** [moosefs/moosefs#492]
System information
centos7 5.4.210-1.el7.elrepo.x86_64
moosefs 3.0.116
nfs-utils-1.3.0-0.68

![image](https://user-images.githubusercontent.com/43692993/188844626-10e8cf0a-c2b3-464e-8427-f0d7ff222ddb.png)

**Comment by xandrus** [comment]
Hi,

basically, you are testing caches not real transfer.
Use oflag with dd to run your tests.

`time dd if=/dev/zero of=test/test3.db bs=8k count=500000 oflag=direct`

Please note that the NFS server is not a distributed file system and, in your case, uses a loopback rather than a true network interface.
