### ISSUE TITLE
Please re-license as GPL-2+

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#5]
License grant says that MooseFS is GPL-2 (only). This is bad practice. Please consider re-licensing as GPL-2+ (_or (at your option) any later version_).

**Comment by onlyjob** [comment]
GPL-2+ gives maximum compatibility. We just need to follow official GPL recommendations: https://www.gnu.org/licenses/gpl-howto.html

See also http://gplv3.fsf.org/rms-why.html

I think licensing as GPL-2 (only) is a very bad practice...

**Comment by onlyjob** [comment]
I really hope that problem could be addressed. Is GPL-2 is a deliberate choice for incompatibility with LizardFS, licensed as GPL-3+? Allowing upgrade of license is useful. I wouldn't like to contribute any code licensed as GPL-2 only...

**Comment by acid-maker** [comment]
We can talk about it internally, but personally I don't like GPLv3.

When we released our first GPL'ed MooseFS (version 1.5) I just picked GPLv3 without reading because it was the newest one, so it seemed that it is the best one. Then somebody made fork of my software not because he wanted to contribute, but because he wanted to make money. This is in my opinion totally AGAINST idea of free software. Then I've totally lost my faith in free software - and because of that we changed licence to "proprietary". Now I know that it was totally bad decision. After year or so one of our contributor (Davies Liu) contacted me and he convinced me that it was a bad decision and we should back to GPL (or similar) licence. He also wrote me that we should consider back to GPL but to version 2. The main reason is not all DRM/Tiviolation stuff (which I don't care - we may add this to our GPLv2) but patents. He told me that programmers who are hired in big companies sometimes are not allowed to contribute to GPLv3 because companied are afraid of loosing their patents. This time I tried to choose licence more carefully. I tried to compare them and it seems that personally I like GPLv2 more than GPLv3. It also seems that GPLv2 is more pro-community than GPLv3 (because of patents provisions).

Incompatibility with Lizard was mere a bonus. Now it doesn't matter - they changed my code almost totally. I doubt that they might even consider taking code from current MooseFS. They still can copy ideas and good ideas are much more important than just bunch of C instructions. It even would be easier for them to implement my ideas in C++ than copy my C code.

Of course you may try to convince me to change the licence to GPLv2+, but it should be something more essential than just good practice. Even Linus Torvalds is against GPLv3, so maybe this is not very good licence?

**Comment by onlyjob** [comment]
If you want to be convinced then please use common sense and read more about GPL-3.
I won't put much effort in this but here are some thoughts:

 * GPL-2+ means GPL-2 or GPL-3 so compatibility is great, everyone is happy and flexibility is fantastic.

 * Incompatibility with LizardFS is not a bonus. At the moment you have more to lose as LizardFS@github have 261 stars, 76 forks and 27 contributors versus MooseFS with 31 star, 2 forks and 3 contributors. I know that github project is young but still... License compatibility is a big plus. Besides lizardFS is ahead of MooseFS and the latter have a lot to catch-up with...

 * Personally I feel disinclined to contribute to GPL-2 licensed project. IMHO GPL-2 licensing is disadvantage in long term. To me this is a pressing issue and I feel that it does not worth the effort to invest into GPL-2 locked project.

 * Linus Torvalds is wrong about GPL-2+ and he have (personal?) issues with FSF. Also Linus is in minority about that while world is moving towards GPL-3+. Soon enough you may find yourself not being able to use GPL-3+ libraries and that might turn out as big disadvantage and hurt MooseFS badly.  GPL-2 licensing is an abuse of copyleft ideas and a time bomb: it will be difficult to upgrade the license without consent from all contributors unless you change license to GPL-2+ (or GPL-3+) ASAP.

 * You misunderstand intentions of GPL-3 and so do people who reluctant to contribute to GPL-3+ projects. In this particular case GPL-2+ gives you greater flexibility to accept contributions from those who can't give to GPL-3+ (e.g. LizardFS). Patents concerns are certainly misplaced. GPL-3 offers better protection from abuse than GPL-2 and this is important for long term survival of the project. Or maybe even for short term survival...

 * Try risk assessment. What do you have to lose from GPL-2+? Nothing. And a lot to gain.
What do you gain from staying on GPL-2? Nothing. And a lot to lose...

**Comment by onlyjob** [comment]
Simply adding `or (at your option) any later version` addresses the problem nicely so you can comfortably stay with GPL-2+ as long as necessary while allowing those who wish to distribute MooseFS to upgrade license or combine code with (L)GPL-3. GPL-2 (only) is just too restrictive.

**Comment by Zorlin** [comment]
+1 to all of what @onlyjob said. 

As to LizardFS vs MooseFS, any bad blood between the two projects is not productive. Both teams do great work.

**Comment by SIN3R6Y** [comment]
If this is still up for consideration i would personally recommend something like MPL2.0, it would allow the authors of MooseFS to avoid the things they could potentially dislike about GPLv3, but also maintain a wider sense of compatibility. Also you get to keep the copyleft aspects, although it could be considered a bit weaker as it is file based rather than project based. Personally i don't think the file based copyleft issue is all that bad, if someone comes along and adds a bunch of cruft that requires adding a ton of new files to the project you likely aren't interested in those changes anyways.

**Comment by onlyjob** [comment]
What "expiring" means?

**Comment by borkd** [comment]
> What "expiring" means?
It is a housekeeping label to solicit feedback after long period of inactivity. If you place the mouse over the label, it will say "Has seen no updates in a while and will be closed."

**Comment by onlyjob** [comment]
Thanks. But it helps nothing to close the ticket without doing anything about the problem... Even if nobody could address the issue in a while...

**Comment by onlyjob** [comment]
https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29

**Comment by chogata** [comment]
The decision was made a long time ago and for various reasons MooseFS stays with GPLv2. This is a legal-related decision and as such will not be discussed in an open forum. This topic is obsolete and should have been closed already.

**Comment by onlyjob** [comment]
If you appreciate transparency then open forum is the right place to discuss such things. You have made a mistake. Please reconsider.
