### ISSUE TITLE
[BUG] Newly created files with leading 0 bytes 

### ISSUE THREAD

**Issue by diomedesadmin** [moosefs/moosefs#576]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
Ubuntu 20.04 PPA x64
version: 3.0.117-1 ; build: 1341
for all master,metalogger and chunkservers

#### Operating system (distribution) and kernel version.
Ubuntu 2004
5.4.0-182-generic

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.
Server1: 128CPUs , 504GB RAM running: master + metalogger + chunkserver1
Server2: 128 CPUS, 504GB RAM running: chunkserver2
Server3:  128CPUs, 504GB RAM, running: chunkserver3

#### How much data is tracked by moosefs master (order of magnitude)?
```
+--------------------------------------------------+
|                   Master Info                    |
+-----------------------+--------------------------+
| master version        |                  3.0.117 |
| RAM used              |                  9.6 GiB |
| CPU used              |                   41.35% |
| CPU used (system)     |                   31.73% |
| CPU used (user)       |                    9.63% |
| total space           |                  195 TiB |
| avail space           |                  123 TiB |
| free space            |                  123 TiB |
| trash space           |                  1.0 TiB |
| trash files           |                  2568508 |
| sustained space       |                      0 B |
| sustained files       |                        0 |
| all fs objects        |                 31078512 |
| directories           |                  9115799 |
| files                 |                 20793020 |
| chunks                |                 20121983 |
| all chunk copies      |                 20121983 |
| regular chunk copies  |                 20121983 |
| last successful store | Tue Jun 18 14:00:23 2024 |
| last save duration    |                   ~23.0s |
| last save status      |      Saved in background |
+-----------------------+--------------------------+
```

## Describe the problem you observed.

Randomly, newly created files have leading zero bytes, for example:

File: ./tkxxx.data, Leading Zero Bytes: 33176300

The output files should have 1560 bytes, but its size on disk is 33177860 . There are 33176300 (33177860 - 1560) leading 0 bytes, and the actual file content starts after this.

```
# mfsfileinfo -c tkxxx.data
 tkxxx.data:
        chunk 0: 0000000001A066EB_00000001 / (id:27289323 ver:1)
                copy 1: 192.168.0.5:9422 (status:VALID ; blocks: 507 ; checksum digest: 92236B42DB9EF61ABD5D63A3BB79D071)
```

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

It happens randomly.

#### Include any warning/errors/backtraces from the system logs.
We have none.

**Comment by chogata** [comment]
Nothing happens randomly in MooseFS master, as it is a single threaded process. So, if those files with leading zeros appear seemingly randomly, there has to be another factor.
First very important question: what version of FUSE do you have installed on your system: 2 or 3? If you still have version 2, upgrade to 3 and see if the problem is still there. We don't support FUSE 2 any longer, as it has a lot of issues with cache, parallel access to files, append operation in general etc.
If you have FUSE 3 and the problem still exists:
How are those files created? What process is recording them? Is there a possibility that 2 or more processes are trying to write to the same file?
How often does it happen? Are you able to "catch" the creation of such a file? Oplog information gathered during recording would probably answer the question of where the zeros come from. There are 2 ways of obtaining oplog information:
1) In the directory where your MooseFS instance is mounted, you can start reading `.oplog` file and record it to some location. Then, as soon as a file with extra zeros is created, you can stop recording.
2) After you spot a creation of a file with extra zeros, you need to immediately record the `.ophistory` file from the directory where your MooseFS instance is mounted. "Immediately" means quick enough so the `.ophistory` still has relevant info. The .ophistory is only guaranteed to hold 15k lines of operation logs (it may have more if there is space available, but only 15k is guaranteed).
Once you have this file, post it (or a link) here and also the name and path (or just inode) of the file with extra zeros and I will help you trace what has happened.

**Comment by diomedesadmin** [comment]
We cannot reproduce it anymore. Will reopen if it appears.
