### ISSUE TITLE
ec41 LABEL definition and ambiguous archivability status "EC KEEP ONLY"

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#610]
I have modified storage class with `-A @4+1,P+Q+U,M -m STRICT` (or `-A @4+1,P+P+Q+U,M -m STRICT`): the intent is to have EC chunks on any chunkservers labelled `P`, `Q` or `U` plus parity chunk on `M`.
There are two chunkservers `P`, one `Q`, one `U`. Few `M` chunkservers are on the same server (that's why I only want parity chunk on `M`). 

However, _Resources/achievable_ says `EC KEEP ONLY` -- what does that mean? (Is this status documented anywhere?)

Since, archiveability `YES` is expected instead of `EC KEEP ONLY`, what would be the correct LABEL EXPRESSION for `ec(P,P,Q,U)+M` ?

Thanks.

**Comment by chogata** [comment]
The status itself is not yet described anywhere, as we are in the middle of re-designing our GUI. However, if you read the manual page https://moosefs.com/manpages/mfsscadmin "LABEL MODES" section, you will find this information:

> In general, chunks will only be converted from copy format to EC format if there are enough servers in the system to safely store all the parts of the EC format. For EC @N+X format, where N is number of data parts and can be either 4 or 8 and X is number of parity/checksum parts and can be equal to 1 (CE version) or any number from 1 to 9 (PRO version), the general requirements are:
> - at least N+2X chunk servers to convert new chunks from copy format to EC format
> - at least N+X chunk servers to keep chunks that are already in EC format still in this format
> - if there are less than N+X servers, all chunks will revert to copy (KEEP definition) format.

So for EC4+1:
- 6 servers or more - data is converted to EC ("YES" status in GUI)
- 5 server - data is kept in EC if it's already in EC ("EC KEEP ONLY" status in GUI)
- 4 server or less - data is converted back to copy format and kept in copies ("NO" status in GUI)

Why? The answer is simple: EC4+1 format is supposed to survive 1 server failure. With exactly 5 servers, if one fails, there are 4 left and no server to record the 5th part to. Therefore 5 servers is not enough for "sane" storage of this format. So we don't do new conversions, but we also do not rush to convert back what is already in EC, because we hope the 6th server will appear soon.

This was the simplest case, now we add labels. In "LOOSE" and "NORMAL" modes we are allowed, in case of emergency, to record a part on a "wrong" label. Therefore we only care that we have at least 4 servers with labels for data parts, 1 server with labels for parity part and 1 "spare" server with either data or parity labels, to the total of 6.

When you use "STRICT" on top of your definition and you use different labels for data parts and different labels for parity parts, you actually require one extra server from each group: if one of the data part servers fails, we need an extra one to restore data parts to, if one of the parity part servers fails, we need an extra one to restore parity parts to. If we don't have them, then we are in the middle state: current EC chunks are kept as they are, but no new ones are created.

And that is exactly what happens in your instance: you have a spare for parity parts, because you have more than one M, but you don't have a spare for data parts, because you have exactly 4 servers for data parts: 2 x P, U and Q. If one of them fails, the system should restore the missing data parts somewhere, but there is no server to restore them too. This is not a "sane" situation for MooseFS, so it will not convert new chunks to EC with this definition.

So, the solution is to add 1 more server to the pool of servers designed for data parts.
