### ISSUE TITLE
mmap does not work on Mac (by default)

### ISSUE THREAD

**Issue by davies** [moosefs/moosefs#66]
The direct-io mode in osxfuse breaks mmap [1], it could be workaround by switch to other cachemode, for example, auto.

Is there any problem with using mfscachemode=auto in Mac?

[1] https://github.com/osxfuse/osxfuse/issues/223#issuecomment-166567092

**Comment by acid-maker** [comment]
In the past OSXFUSE ignored 'keep_cache' flag in the 'open' call (always kept everything in the cache). This is why I introduced using direct io as a default on OS X. Direct io is also set by default on FreeBSD, but because of inefficiences in cache code - mainly using 4k block for every I/O which is very slow.

I've checked it today and now it seems to work fine. If mmap doesn't work with direct I/O (which is possible and even logical to some point) then I think that we should switch back defaults to 'auto' mode for cache on OS X and leave 'direct' mode only on FreeBSD.

BTW. On OS X 'direct' mode is also little faster than 'auto' mode. On my Mac (localhost,SSD):
'auto' - read and write: about 240MB/s
'direct' - read: 750MB/s (chunks likely in cache) / write: 520MB/s
So if you don't need mmap and rarely read the same files then you should use direct-io on the Mac, but of course by default it is better to support mmap than make it more efficient.

**Comment by davies** [comment]
@acid-maker git reply on mmap, so 'auto' mode sounds better default to me, thanks!
