### ISSUE TITLE
Upgrade path from MooseFS 2 to Moosefs 3? 

### ISSUE THREAD

**Issue by kbarmen** [moosefs/moosefs#70]
It has always been a mystery for me what the real differences between 2.0 and 3.0 are, and why one would want to pick 2.0 over 3.0. Anyways, we have a handful of clusters running 2.0.91, and with support for 2.0 ending now in December, we are pondering on the path forward.

This may be a silly question with an obvious answer for those who play with it every day, so pardon my ignorance :)

Is upgrading from 2.x to 3.x a simple matter of in-place upgrading master, meta-loggers, chuck-servers and clients (in that order) from 2.0.91 to 3.0.97?

I have search high and low, but only found a doc describing upgrading from 1.6 to 2.0.

Cheers!

**Comment by xandrus** [comment]
Hi.
Basically the bisggest changes in MooseFS 3.0 are:
- added support for labels (storage tiering)
- improvements connected with small files operations
- many bug fixes and improvements: https://moosefs.com/documentation/changes-in-moosefs-3-0.html

According to upgrade from 2.0 to 3.0. 
Upgrade scenario is the same as in upgrade from 1.6 to 2.0.
Upgrade is very simple and as you said "it's matter of in-place update"

Most importan aspect in upgrade process is to start from MooseFS master, because only new master 3.0 is able to communicate with older components:

As reference you can use this document:
https://moosefs.com/Content/Downloads/moosefs-upgrade.pdf
