### ISSUE TITLE
error log mfs version 2.0.71

### ISSUE THREAD

**Issue by zhs077** [moosefs/moosefs#71]
Sep 25 16:37:51 mfsmount[8535]: file: 67538105, index: 0, chunk: 1109490528, version: 1 - writeworker: connection with (127.0.0.85:9422) was reset by peer / ZEROREAD (unfinished writes: 2; try counter: 1)
Sep 25 16:41:19 mfsmount[8535]: file: 97492657, index: 0, chunk: 1106020034, version: 1 - writeworker: connection with (127.0.0.89:9422) was timed out (unfinished writes: 2; try counter: 1)
Sep 25 16:41:35 mfsmount[8535]: file: 97494034, index: 0, chunk: 1106020355, version: 1 - writeworker: connection with (127.0.0.86:9422) was timed out (unfinished writes: 2; try counter: 1)
Sep 25 16:41:38 mfsmount[8535]: file: 97869978, index: 0, chunk: 1106169979, version: 1 - writeworker: connection with (127.0.0.83:9422) was timed out (unfinished writes: 2; try counter: 1)
Sep 25 16:41:56 mfsmount[8535]: file: 94598427, index: 0, chunk: 1106171338, version: 1 - writeworker: connection with (127.0.0.86:9422) was timed out (unfinished writes: 2; try counter: 1)
Sep 25 16:42:41 mfsmount[8535]: file: 14383188, index: 0, chunk: 1106858083, version: 1 - writeworker: connection with (127.0.0.93:9422) was timed out (unfinished writes: 2; try counter: 1)
Sep 25 16:43:02 mfsmount[8535]: file: 97557752, index: 0, chunk: 1106038519, version: 1 - writeworker: connection with (127.0.0.89:9422) was timed out (unfinished writes: 3; try counter: 1)

**Comment by zhs077** [comment]
how can i found more error info

**Comment by zcalusic** [comment]
I started having these errors recently (last 2 weeks), too. I don't remember seeing them before. In my case, MooseFS 3.0.97, the latest and greatest.

In one case it was possibly due to low upload bandwidth, I've seen try counter go up to 30, before I/O errors were returned to rsync process that was accessing mfs. Other times, the bandwidth was ample.

In some cases this also resulted in corrupted files, and that is a bit frightening. I'd appreciate any comment on the errors, too.

**Comment by xandrus** [comment]
Hi.
Time out in TCP/IP is nothing unusual. 
It can mean that chunkservers are have loaded, or network traffic is high.

@zcalusic 
According to "try counter: 30". This is our limit so you will always get I/O error.
Question is what is causing such a behavior? 

Can you give us some more detailed information - system log, dmesg.
Is it possible that one of your chunkserver has brocken hdd?

**Comment by zcalusic** [comment]
@xandrus, HDD is fine, no problem, and also nothing worth mentioning in dmesg. The hardware seems completely OK. I'm inclined to think this is a network (bandwidth) problem. Things like that can happen, as you also point out. I was only worried that in some cases it resulted in corrupted file, which could point to some bug in the code.

Now that I mention it, I also have ```mfscachemode=YES, mfsentrycacheto=30, mfsattrcacheto=30, mfsdirentrycacheto=30``` settings for every mount. This could've probably introduced corruption. Blocks haven't finished on the remote storage (due to timeout and eventually I/O error), yet local cache can claim they have. It can easily confuse rsync to not send data that really needs to be (re)sent. I now don't even remember why I have put those settings, but probably because they provided much improved performance for some use cases.

I really don't have anything else to report.

**Comment by xandrus** [comment]
@zcalusic , thank you for all this information. I have last question. Your chunkservers are using ext4 or xfs filesystem?

**Comment by xandrus** [comment]
I can only suggest to use this mount options for EXT4:
`mount -t ext4 -o defaults,nodiratime,commit=10,nodelalloc,nouser_xattr /dev/sd[x] /mnt/chunks[x]`
The can speed up some EXT4 operations - mostly delete opearations.

**Comment by zcalusic** [comment]
Cool @xandrus, thanks for the tip. I'll consider the extra options for improved performance.

Though, when it comes to performance, I'm a happy camper already. 😄
