### ISSUE TITLE
Archive based on last access time

### ISSUE THREAD

**Issue by ghost** [moosefs/moosefs#77]
It'd be good if you could archive based on last access time as opposed to modification time

**Comment by oxide94** [comment]
Hi @jacksenk,

I forwarded your idea to our dev team. Next week we will think about it and let you know.

Thanks,
Peter / MooseFS Team

**Comment by jacksenk** [comment]
Any decision made?

If no, is it possible to make a custom plugin to the master server to do
so?

**Comment by oxide94** [comment]
Hi @jacksenk,
we discussed it internally and it is possible that we will add such possibility in MooseFS 4.0

Peter / MooseFS Team

**Comment by jacksenk** [comment]
Awesome to hear

On 25 Nov. 2017 11:57 am, "Piotr Robert Konopelko" <notifications@github.com>
wrote:

Hi @jacksenk <https://github.com/jacksenk>,
we discussed it internally and it is possible that we will add such
possibility in MooseFS 4.0

Peter / MooseFS Team

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/moosefs/moosefs/issues/77#issuecomment-346910275>, or mute
the thread

**Comment by oxide94** [comment]
Hi @jacksenk,

I wanted to let you know that it is already implemented and in MooseFS 4.x you will be able to set the archive mode basing on `ctime`, `atime` and `mtime`.

Best regards,
Peter / MooseFS Team

**Comment by jacksenk** [comment]
Thanks for the update

**Comment by 4Dolio** [comment]
Nice! I think I could use that feature... ;)

**Comment by chogata** [comment]
Feature implemented in MooseFS 4 - please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).
