### ISSUE TITLE
error in moosefs -- SIGBUS

### ISSUE THREAD

**Issue by com4343568** [moosefs/moosefs#95]
Currently I am working on a DNA sequencing project, moosefs is choosed as a back-end shared storage system. The sequencing tasks are distributed on 300 computing servers, all the servers are mounted on moosefs(built by 160 chunk servers, version 3.0.92).

Sometimes the SIGBUS error shows up, my task will be crashed. When I check the core file, it shows:
![e wv3 s8wbg1d2 fznh_moj](https://user-images.githubusercontent.com/21219088/36931570-ab186684-1ef3-11e8-8ece-459a3fefaad5.png)

 At the crash time point, the moosefs(client) log is shown below:
<img width="1269" alt="d15f0e83-5102-40aa-af72-7163edd909bd" src="https://user-images.githubusercontent.com/21219088/36931594-0b0f878e-1ef4-11e8-9f3f-00ea380e67e5.png">

MFSmaster log:
<img width="949" alt="7484c1f3-c79f-415f-9fb0-0bd03858fdfb" src="https://user-images.githubusercontent.com/21219088/36931639-68ebe608-1ef5-11e8-883b-a9d2cc4ee09c.png">

Some related info:

- Mount config

     mfsmount /mnt -H xxx -o mfscachemode=always -o mfswritecachesize=2048 -o mfsentrycacheto=60 -o mfsattrcacheto=60 -o mfsxattrcacheto=300 -o mfsdirentrycacheto=60 -o mfsnegentrycacheto=60

- MFSmaster config
<img width="1245" alt="c2acdb40-29a0-4f9c-ae65-c234fb11b77f" src="https://user-images.githubusercontent.com/21219088/36931614-98b5ef7e-1ef4-11e8-8ad8-964197f3a9c9.png">

1. how could I solve this problem?

2. what is grace mode? When a chunkserver is changed to grace mode, is it still readable or objects will be read from duplication?

Thanks a Million !

**Comment by oxide94** [comment]
Hi @com4343568,

Thank you for this report.

First and foremost: your Master Server config is really improper. Your replication limits and other options are set to like infinity. This is not good. First of all please come back to default values (especially `CHUNKS_SOFT_DEL_LIMIT`, `CHUNKS_HARD_DEL_LIMIT`, `CHUNKS_WRITE_REP_LIMIT`, `CHUNKS_READ_REP_LIMIT`):

```
REPLICATIONS_DELAY_INIT = 300

CHUNKS_SOFT_DEL_LIMIT = 10
CHUNKS_HARD_DEL_LIMIT = 25

CHUNKS_WRITE_REP_LIMIT = 2,1,1,4
CHUNKS_READ_REP_LIMIT = 10,5,2,5

CS_HEAVY_LOAD_THRESHOLD = 100
CS_HEAVY_LOAD_RATIO_THRESHOLD = 5.0
CS_HEAVY_LOAD_GRACE_PERIOD = 900
```

Why have you changed these parameters to such huge values?

Default parameters are chosen to be optimal even in big clusters (like petabytes), as we are using MooseFS ourselves and have such MooseFS instances. Changing them to such huge numbers as you did may make MooseFS unstable (and I can see in your logs it essentially did so).

Secondly, please upgrade your whole cluster to the newest version (3.0.100) and let us know if issue persists. MooseFS 3.0.92 was released almost a year ago (see changelog [here](https://github.com/moosefs/moosefs/blob/master/NEWS#L71)) and we have fixed many issues since then.

Thank you,

Best regards,
Peter / MooseFS Team

**Comment by oxide94** [comment]
Hi @com4343568,
did it help you to resolve the issue?

Thanks,
Best regards,
Peter / MooseFS Team

**Comment by com4343568** [comment]
Hi Peter,
thansks for your help, finally I slove the problem by setting chunkserver wokers number to 10000.

**Comment by oxide94** [comment]
Hi @com4343568,

I'm glad my suggestions helped you. In case of any further issues, please don't hesitate to ask.

Thanks,
Best regards,
Peter / MooseFS Team
